### PR TITLE
Bump dataplane operator to fix EDPM CI jobs

### PR DESCRIPTION
**Pull request by rabi**
Depends-On: https://github.com/openstack-k8s-operators/install_yamls/pull/524

### CODE REVIEW

**Review by cjeanner — APPROVED** [review]

**Comment by rabi** [comment]
make: *** [Makefile:417: crc_storage] Error 1

**Comment by rabi** [comment]
2023-09-08T08:35:31.607304993+00:00 stdout F TASK [osp.edpm.edpm_network_config : Render network_config from template] ******
2023-09-08T08:35:31.608455320+00:00 stdout F Friday 08 September 2023  08:35:31 +0000 (0:00:00.157)       0:01:00.536 ****** 
2023-09-08T08:35:32.169891346+00:00 stdout F [0;31mAn exception occurred during task execution. To see the full traceback, use -vvv. The error was: ValueError: Invalid type provided for "string": {'template': 'templates/single_nic_vlans/single_nic_vlans.j2'}[0m
2023-09-08T08:35:32.169891346+00:00 stdout F [0;31mfatal: [edpm-compute-0]: FAILED! => {"msg": "Unexpected failure during module execution: Invalid type provided for \"string\": {'template': 'templates/single_nic_vlans/single_nic_vlans.j2'}", "stdout": ""}[0m

**Comment by rabi** [comment]
recheck

**Comment by cjeanner** [comment]
right, old job will need some attention as well -.-...

**Comment by rabi** [comment]
> right, old job will need some attention as well -.-...

https://github.com/openstack-k8s-operators/install_yamls/pull/524

**Comment by cjeanner** [comment]
Also trying with https://github.com/openstack-k8s-operators/ci-framework/pull/533

**Comment by pablintino** [comment]
recheck

**Comment by fao89** [comment]
it seems to be a real failure:
```
2023-09-08T10:34:10.667558475+00:00 stdout F TASK [osp.edpm.edpm_network_config : Render network_config from template] ******
2023-09-08T10:34:10.668816944+00:00 stdout F Friday 08 September 2023  10:34:10 +0000 (0:00:00.193)       0:04:42.315 ****** 
2023-09-08T10:34:11.127426071+00:00 stdout F [0;31mAn exception occurred during task execution. To see the full traceback, use -vvv. The error was: ValueError: Invalid type provided for "string": {'template': 'templates/single_nic_vlans/single_nic_vlans.j2'}[0m
2023-09-08T10:34:11.127426071+00:00 stdout F [0;31mfatal: [edpm-compute-0]: FAILED! => {"msg": "Unexpected failure during module execution: Invalid type provided for \"string\": {'template': 'templates/single_nic_vlans/single_nic_vlans.j2'}", "stdout": ""}[0m
```
https://logserver.rdoproject.org/58/458/7cd507f8d3ffaa26d1624cb46fb3aad48a919d61/github-check/openstack-operator-crc-podified-edpm-deployment/a28bb72/ci-framework-data/logs/crc/pods/openstack_dataplane-deployment-configure-network-openstack-edpm-r7knr_9b898dc0-a60a-4a3a-8dab-107f67a954e4/openstackansibleee/0.log

**Comment by pablintino** [comment]
> it seems to be a real failure:
> 
> ```
> 2023-09-08T10:34:10.667558475+00:00 stdout F TASK [osp.edpm.edpm_network_config : Render network_config from template] ******
> 2023-09-08T10:34:10.668816944+00:00 stdout F Friday 08 September 2023  10:34:10 +0000 (0:00:00.193)       0:04:42.315 ****** 
> 2023-09-08T10:34:11.127426071+00:00 stdout F �[0;31mAn exception occurred during task execution. To see the full traceback, use -vvv. The error was: ValueError: Invalid type provided for "string": {'template': 'templates/single_nic_vlans/single_nic_vlans.j2'}�[0m
> 2023-09-08T10:34:11.127426071+00:00 stdout F �[0;31mfatal: [edpm-compute-0]: FAILED! => {"msg": "Unexpected failure during module execution: Invalid type provided for \"string\": {'template': 'templates/single_nic_vlans/single_nic_vlans.j2'}", "stdout": ""}�[0m
> ```
> 
> https://logserver.rdoproject.org/58/458/7cd507f8d3ffaa26d1624cb46fb3aad48a919d61/github-check/openstack-operator-crc-podified-edpm-deployment/a28bb72/ci-framework-data/logs/crc/pods/openstack_dataplane-deployment-configure-network-openstack-edpm-r7knr_9b898dc0-a60a-4a3a-8dab-107f67a954e4/openstackansibleee/0.log
> 
> maybe the depends-on was added after the run?

Maybe, the current run has already passed that step successfully. I rechecked cause I saw a timeout error from etcd that made the CR apply step to fail.

**Review by slagle — APPROVED** [review]

**Pull request merged**
