### PR TITLE
[OSPRH-8473] Warning: unknown field "spec.telemetry.template.logging.…

### PR DESCRIPTION
**Pull request by jlarriba**
…network"

### CODE REVIEW

**Comment by snecklifter** [comment]
@jlarriba rather than just remove the line, would it be possible to replace it with an annotation example?

**Comment by jlarriba** [comment]
@snecklifter I dont think I like that idea: the annotations are configured exactly identical in all the operators (we are all reusing the same framework) and none of the rest have them in these examples. I think the idea is to try to keep the yaml example files not too verbose. The annotation usage could be documented in the official documentation, in a common section.

**Comment by abays** [comment]
> Sorry, i have realized that there are actually examples where they have them. We could do it to show that there is that possibility. I am going definitively to add the annotations field to some of the samples.

It looks good to me.  Should we wait for this additional change before approving?

**Comment by jlarriba** [comment]
> > Sorry, i have realized that there are actually examples where they have them. We could do it to show that there is that possibility. I am going definitively to add the annotations field to some of the samples.
> 
> It looks good to me. Should we wait for this additional change before approving?

Yes please

**Comment by jlarriba** [comment]
@abays now its ready

**Review by abays — APPROVED** [review]
/lgtm

**Comment by jlarriba** [comment]
recheck

**Comment by jlarriba** [comment]
recheck

**Comment by jlarriba** [comment]
Kuttl fix: https://github.com/openstack-k8s-operators/telemetry-operator/pull/451

**Pull request merged**
