### PR TITLE
Add data plane adoption job to openstack-operator

### PR DESCRIPTION
**Pull request by cescgina**

### CODE REVIEW

**Comment by cescgina** [comment]
recheck

**Comment by cescgina** [comment]
recheck

**Review by fao89 — APPROVED** [review]

**Comment by abays** [comment]
recheck

**Comment by cescgina** [comment]
recheck

**Comment by fao89** [comment]
all the tests passed individually in different runs,
@abays could you please override and approve?

**Comment by jistr** [comment]
Thanks :+1:

**Review by dprince — APPROVED** [review]

**Pull request merged**
