### PR TITLE
Sync galera config samples

### PR DESCRIPTION
**Pull request by dciabrin**
Add Swift and Heat to the deployment.
Add a 3-replica sample for network isolation.

### CODE REVIEW

**Review by abays — APPROVED** [review]
/lgtm

**Comment by abays** [comment]
recheck

**Review by raukadah — APPROVED** [review]
Tested it here: https://github.com/openstack-k8s-operators/install_yamls/pull/375 and 
[install-yamls-crc-podified-deployment](https://review.rdoproject.org/zuul/build/d7ab46ec38d64faf92fd811aa50b9b39) passed.
https://logserver.rdoproject.org/75/375/02ee1c70bf0fb57bfac0b3a8b37f075a033d188a/github-check/install-yamls-crc-podified-deployment/d7ab46e/ci-framework-data/logs/ci_make_003_run_openstack_deploy.log

```
kustomize edit add resource ./core_v1beta1_openstackcontrolplane_galera_network_isolation_3replicas.yaml
```

**Comment by abays** [comment]
recheck

**Comment by abays** [comment]
recheck

**Pull request merged**
