### PR TITLE
Use ServiceNet for ansible vars

### PR DESCRIPTION
**Pull request by rabi**
Jira: https://issues.redhat.com/browse/OSPRH-10125

### CODE REVIEW

**Review by fao89 — APPROVED** [review]

**Review by fao89 — APPROVED** [review]

**Comment by rabi** [comment]
recheck

**Comment by stuggi** [comment]
I think you'd have to rebase to get https://github.com/openstack-k8s-operators/openstack-operator/pull/1084 ?

**Comment by fao89** [comment]
recheck

**Review by slagle — APPROVED** [review]

**Review by fao89 — APPROVED** [review]

**Pull request merged**
