### PR TITLE
CeilometerCentral api has been renamed to Ceilometer api

### PR DESCRIPTION
**Pull request by jlarriba**

### CODE REVIEW

**Comment by abays** [comment]
> @jlarriba: The following test **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:
> Test name 	Commit 	Details 	Required 	Rerun command
> ci/prow/openstack-operator-build-deploy-kuttl 	[c04f0ff](https://github.com/openstack-k8s-operators/openstack-operator/commit/c04f0ffa416dfef98ed92e1f1f1b76899a89dfc4) 	[link](https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openstack-k8s-operators_openstack-operator/466/pull-ci-openstack-k8s-operators-openstack-operator-main-openstack-operator-build-deploy-kuttl/1702308425683177472) 	true 	`/test openstack-operator-build-deploy-kuttl`
> 
> [Full PR test history](https://prow.ci.openshift.org/pr-history?org=openstack-k8s-operators&repo=openstack-operator&pr=466). [Your PR dashboard](https://prow.ci.openshift.org/pr?query=is:pr+state:open+author:jlarriba).

It looks like the `Ceilometer` `Deployment` resource is failing to spawn its associated `Pod`.  I see this in the pod logs:

```
Warning  FailedMount  60s (x16 over 17m)  kubelet            MountVolume.SetUp failed for volume "sg-core-conf-yaml" : configmap references non-existent config key: sg-core.conf.yaml
```

**Comment by jlarriba** [comment]
Yes, looking at it

> > @jlarriba: The following test **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:
> > Test name 	Commit 	Details 	Required 	Rerun command
> > ci/prow/openstack-operator-build-deploy-kuttl 	[c04f0ff](https://github.com/openstack-k8s-operators/openstack-operator/commit/c04f0ffa416dfef98ed92e1f1f1b76899a89dfc4) 	[link](https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openstack-k8s-operators_openstack-operator/466/pull-ci-openstack-k8s-operators-openstack-operator-main-openstack-operator-build-deploy-kuttl/1702308425683177472) 	true 	`/test openstack-operator-build-deploy-kuttl`
> > [Full PR test history](https://prow.ci.openshift.org/pr-history?org=openstack-k8s-operators&repo=openstack-operator&pr=466). [Your PR dashboard](https://prow.ci.openshift.org/pr?query=is:pr+state:open+author:jlarriba).
> 
> It looks like the `Ceilometer` `Deployment` resource is failing to spawn its associated `Pod`. I see this in the pod logs:
> 
> ```
> Warning  FailedMount  60s (x16 over 17m)  kubelet            MountVolume.SetUp failed for volume "sg-core-conf-yaml" : configmap references non-existent config key: sg-core.conf.yaml
> ```

**Comment by abays** [comment]
recheck

**Comment by jlarriba** [comment]
recheck

**Review by abays — APPROVED** [review]
/lgtm

**Pull request merged**
