### PR TITLE
Bump dataplane-operator

### PR DESCRIPTION
**Pull request by rabi**
To include tlse fix https://github.com/openstack-k8s-operators/dataplane-operator/pull/812

jira: https://issues.redhat.com/browse/OSPRH-6266

### CODE REVIEW

**Review by abays — APPROVED** [review]
/lgtm

**Comment by abays** [comment]
> @rabi: The following test **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:
> Test name 	Commit 	Details 	Required 	Rerun command
> ci/prow/openstack-operator-build-deploy-kuttl 	[b32bbbc](https://github.com/openstack-k8s-operators/openstack-operator/commit/b32bbbc51a7eb6e63b8130ef006fa0beda4d6c69) 	[link](https://prow.ci.openshift.org/view/gs/test-platform-results/pr-logs/pull/openstack-k8s-operators_openstack-operator/747/pull-ci-openstack-k8s-operators-openstack-operator-main-openstack-operator-build-deploy-kuttl/1778361687187918848) 	unknown 	`/test openstack-operator-build-deploy-kuttl`
> 
> [Full PR test history](https://prow.ci.openshift.org/pr-history?org=openstack-k8s-operators&repo=openstack-operator&pr=747). [Your PR dashboard](https://prow.ci.openshift.org/pr?query=is:pr+state:open+author:rabi).

/test openstack-operator-build-deploy-kuttl

Keystone hit the DBSync error that @zzzeek is looking into (and might be fixing via [1]):

```
    message: 'DBsync job error occurred Internal error occurred: Job Failed. Check
      job logs'
```

[1] https://github.com/openstack-k8s-operators/mariadb-operator/pull/216

**Comment by karelyatin** [comment]
May be can take https://github.com/openstack-k8s-operators/openstack-operator/pull/746 instead as contains other updates too

**Comment by abays** [comment]
> May be can take #746 instead as contains other updates too

Cool.  #746 has passed CI and should be merged soon.

**Comment by karelyatin** [comment]
/hold

Let's hold it than as taking other one, if that merges other one will get delayed.

**Comment by zzzeek** [comment]
> 
> /test openstack-operator-build-deploy-kuttl
> 
> Keystone hit the DBSync error that @zzzeek is looking into (and might be fixing via [1]):
> 
> ```
>     message: 'DBsync job error occurred Internal error occurred: Job Failed. Check
>       job logs'
> ```
> 
> [1] [openstack-k8s-operators/mariadb-operator#216](https://github.com/openstack-k8s-operators/mariadb-operator/pull/216)

Right so most of what we'd want to see here, like the "successful" db create job, isn't preserved, I'm really wanting to see the output of that job / pod specifically.     I've looked at the status of galera matched with the time the MariaDBDatabase CR had it's job complete, and the CR shows job completion one second before all three galera nodes were synced, which doesnt say much as logs can be off by one second and it could have been using a synced node.    the PR I have would hopefully fix any "silent failure" problems at least since it does a positive check that the database / account got created.

**Comment by karelyatin** [comment]
> @karelyatin Looks like #746 has failed. This one is green. Are we going to followup with that or merge this?

there is issue with prow, ci team is checking. will unhold this and see if this merges and rebase the other one.

**Pull request merged**
