### PR TITLE
Bump infra-operator

### PR DESCRIPTION
**Pull request by rabi**
Required for edpm jobs after https://github.com/openstack-k8s-operators/infra-operator/pull/169

### CODE REVIEW

**Review by abays — APPROVED** [review]
/lgtm

**Comment by abays** [comment]
recheck

Unsure whether this Tempest failure was just a hiccup or not:

```
ResourceNotFound: 404: Client Error for url: https://network.rdo.mtl2.vexxhost.net/v2.0/trunks/522e289c-0685-4c00-8e67-f21ec07e47ad/remove_subports, SubPort 26cd166f-41e8-47ed-a177-c6378a511056 on trunk 522e289c-0685-4c00-8e67-f21ec07e47ad could not be found.
```

**Comment by abays** [comment]
recheck

```
TASK [Gathering Facts] *********************************************************
task path: /usr/share/ansible/collections/ansible_collections/osp/edpm/playbooks/configure_network.yml:
fatal: [compute-1]: UNREACHABLE! => {"changed": false, "msg": "Failed to connect to the host via ssh: ssh: connect to host 192.168.122.101 port 22: No route to host", "unreachable": true}
fatal: [compute-0]: UNREACHABLE! => {"changed": false, "msg": "Failed to connect to the host via ssh: ssh: connect to host 192.168.122.100 port 22: No route to host", "unreachable": true}
fatal: [compute-2]: UNREACHABLE! => {"changed": false, "msg": "Failed to connect to the host via ssh: ssh: connect to host 192.168.122.102 port 22: No route to host", "unreachable": true}
```

**Comment by rabi** [comment]
> recheck
> 
> ```
> TASK [Gathering Facts] *********************************************************
> task path: /usr/share/ansible/collections/ansible_collections/osp/edpm/playbooks/configure_network.yml:
> fatal: [compute-1]: UNREACHABLE! => {"changed": false, "msg": "Failed to connect to the host via ssh: ssh: connect to host 192.168.122.101 port 22: No route to host", "unreachable": true}
> fatal: [compute-0]: UNREACHABLE! => {"changed": false, "msg": "Failed to connect to the host via ssh: ssh: connect to host 192.168.122.100 port 22: No route to host", "unreachable": true}
> fatal: [compute-2]: UNREACHABLE! => {"changed": false, "msg": "Failed to connect to the host via ssh: ssh: connect to host 192.168.122.102 port 22: No route to host", "unreachable": true}
> ```

Yeah  multinode IP Reservation is broken and https://github.com/openstack-k8s-operators/infra-operator/pull/173 should fix it. We probably should add a job with multiple edpm nodes to all repos.

**Comment by rabi** [comment]
recheck

**Pull request merged**
