### PR TITLE
Bind manila-share to the storage network

### PR DESCRIPTION
**Pull request by fmount**
The sample had a wrong networkAttachment in both scheduler and manilaShare. This patch is supposed to fix the NAD part of the template specs.

### CODE REVIEW

**Comment by fmount** [comment]
recheck

**Comment by fmount** [comment]
I think the CI failure is out of scope here, @abays @dprince given this is just a sample file (with the right network fix), we could merge it, it should be safe enough, right?

**Comment by abays** [comment]
recheck

@fmount We could probably just merge it, but unless it's urgent let's try one more time

**Comment by fmount** [comment]
> recheck
> 
> @fmount We could probably just merge it, but unless it's urgent let's try one more time

Not urgent, I'm ok to try even more times :D

**Comment by fmount** [comment]
> recheck
> 
> @fmount We could probably just merge it, but unless it's urgent let's try one more time

@abays safe to merge I guess at this point

**Pull request merged**
