### PR TITLE
Update octavia to include availabilityZone changes

### PR DESCRIPTION
**Pull request by karelyatin**
Required-By: https://github.com/openstack-k8s-operators/architecture/pull/227
Related-Issue: [OSPRH-6901](https://issues.redhat.com//browse/OSPRH-6901)

### CODE REVIEW

**Comment by karelyatin** [comment]
recheck baremetal

**Review by abays — APPROVED** [review]
Approved beta blocker

/lgtm

**Comment by abays** [comment]
Since all the individual Zuul jobs passed between the past two batch attempts, I would be okay with overriding the check here

**Comment by abays** [comment]
recheck

Will try once more

**Comment by karelyatin** [comment]
> Since all the individual Zuul jobs passed between the past two batch attempts, I would be okay with overriding the check here

Yeap should be fine to override, will also unblock some testing

**Comment by karelyatin** [comment]
> @karelyatin: karelyatin unauthorized: /override is restricted to Repo administrators, approvers in top level OWNERS file, and the following github teams:.

So some else with permissions need do it

**Pull request merged**
