### PR TITLE
Fix the CI by fixing sg-core version

### PR DESCRIPTION
**Pull request by jlarriba**

### CODE REVIEW

**Review by abays — APPROVED** [review]
/lgtm

**Comment by abays** [comment]
The Zuul job failure for this PR is not related to the PR itself, but is interesting (data plane deploy times out and this is why): https://logserver.rdoproject.org/83/483/630561852affdc0e906e727f8afff5c324d93f22/github-check/cifmw-crc-podified-edpm-baremetal/42cb974/ci-framework-data/artifacts/must-gather.local.6527883990662920764/quay-io-openstack-k8s-operators-openstack-must-gather-sha256-070a98749455b097c66a1a25ff827a3c0ee7385f1f0c8bf54f5b15438501f2bd/namespaces/openstack/pods/dataplane-deployment-configure-network-openstack-edpm-ipamnclrv/logs/dataplane-deployment-configure-network-openstack-edpm-ipamnclrv.log

**Comment by dprince** [comment]
@jlarriba I just duped this PR because I was looking for 'telemetry-operator' and this PR says 'sg-core'. Whats the deal there?

**Comment by jlarriba** [comment]
Sorry, we were working together on slack and i thought all involved had the context of the issue.

**Pull request merged**
