### PR TITLE
Trim RFC1123 non-compliant chars from pod name

### PR DESCRIPTION
**Pull request by jpodivin**
Resolves: https://issues.redhat.com/browse/OSPRH-8692

### CODE REVIEW

**Review by fao89 — APPROVED** [review]

**Comment by jpodivin** [comment]
recheck

failed during openshift_setup, step `Wait for openshift-marketplace pods to be running`

**Comment by jpodivin** [comment]
recheck

**Comment by jpodivin** [comment]
recheck

**Comment by jpodivin** [comment]
recheck

tempest post failure (HTTP 502)

**Comment by fao89** [comment]
recheck

**Pull request merged**
