### PR TITLE
Bump rabbitmq-cluster-operator-bundle to latest tag

### PR DESCRIPTION
**Pull request by raukadah**
quay.io/openstack-k8s-operators/rabbitmq-cluster-operator-bundle@sha256:49044ebeb92a5bfc3b597b3042d057b63f7c1cddfc5555f2d49780afe228ece0 got bumped via https://github.com/openstack-k8s-operators/openstack-operator/pull/367 is returning unknown manifest.

Bumping it to latest fixes the issue.

### CODE REVIEW

**Review by rabi — COMMENTED** [review]
/lgtm

**Comment by raukadah** [comment]
recheck

**Review by rabi — APPROVED** [review]
/lgtm

**Comment by Sandeepyadav93** [comment]
/approve

Need to unblock CI

**Pull request merged**
