### PR TITLE
Adding the redhat service

### PR DESCRIPTION
**Pull request by fao89**
It will manage RH subscription and Insights
https://linux-system-roles.github.io/rhc/

Depends-On: https://github.com/openstack-k8s-operators/edpm-ansible/pull/837

closes [OSPRH-11938](https://issues.redhat.com//browse/OSPRH-11938)

### CODE REVIEW

**Comment by fao89** [comment]
recheck

**Comment by fao89** [comment]
recheck

**Comment by fao89** [comment]
recheck

**Review by bshephar — APPROVED** [review]

**Pull request merged**
