### PR TITLE
Fix network isolation CR by adding manila

### PR DESCRIPTION
**Pull request by fao89**
```
$make openstack_deploy
oc kustomize /home/faguiard/project/install_yamls/out/openstack/openstack/cr | oc apply -f -
The OpenStackControlPlane "openstack-network-isolation" is invalid: spec.manila.template.manilaShares: Invalid value: "null": spec.manila.template.manilaShares in body must be of type object: "null"
make: *** [Makefile:338: openstack_deploy] Error 1
```

### CODE REVIEW

**Review by stuggi — APPROVED** [review]
/lgtm

**Review by karelyatin — COMMENTED** [review]
i see there are more samples like galera,seperate cell, collapsed cell those don't need similar change?

**Review by dprince — APPROVED** [review]

**Review by gibizer — APPROVED** [review]
Thanks.

**Pull request merged**
