### PR TITLE
Add multipathd image and Fix EDPM $RELATED_IMAGE* vars for consistency

### PR DESCRIPTION
**Pull request by slagle**
This image was missing from OpenStackVersion.

Depends-On: https://github.com/openstack-k8s-operators/dataplane-operator/pull/813
Signed-off-by: James Slagle <jslagle@redhat.com>

### CODE REVIEW

**Comment by dprince** [comment]
Would be good to add the RELATED_IMAGE var for this to hack/export_related_images.sh and then expand the unit test coverage in openstackversion_controller_test.go to ensure the new var is getting set

**Comment by slagle** [comment]
> Would be good to add the RELATED_IMAGE var for this to hack/export_related_images.sh and then expand the unit test coverage in openstackversion_controller_test.go to ensure the new var is getting set

both those are addressed. I'll leave this as draft until the dataplane-operator PR merges

**Comment by slagle** [comment]
recheck

**Comment by slagle** [comment]
Given the inconsistency in the EDPM image env var names, this still wasn't working. Fixing those names here: https://github.com/openstack-k8s-operators/dataplane-operator/pull/813
Then this one can be updated again.

**Comment by slagle** [comment]
> Given the inconsistency in the EDPM image env var names, this still wasn't working. Fixing those names here: [openstack-k8s-operators/dataplane-operator#813](https://github.com/openstack-k8s-operators/dataplane-operator/pull/813) Then this one can be updated again.

That's now merged. This should be ready for review again.

**Review by fao89 — APPROVED** [review]

**Review by dprince — APPROVED** [review]

**Comment by slagle** [comment]
/retest

`
could not run steps: step ansibleee-operator-build-deploy-kuttl failed: failed to wait for the created cluster claim to become ready: timed out waiting for the condition 
`

**Review by dprince — APPROVED** [review]

**Pull request merged**
