### PR TITLE
gofmt fixes

### PR DESCRIPTION
**Pull request by slagle**
fixes from running "make gofmt"

Signed-off-by: James Slagle <jslagle@redhat.com>

### CODE REVIEW

**Comment by bshephar** [comment]
Kuttl failed with:
```
logger.go:42: 22:19:50 |  | Error from server (InternalError): error when creating "https://raw.githubusercontent.com/openstack-k8s-operators/infra-operator/main/config/samples/network_v1beta1_netconfig.yaml": Internal error occurred: failed calling webhook "mnetconfig.kb.io": failed to call webhook: Post "[https://infra-operator-controller-manager-service.openstack-operators.svc:443/mutate-network-openstack-org-v1beta1-netconfig?timeout=10s](https://infra-operator-controller-manager-service.openstack-operators.svc/mutate-network-openstack-org-v1beta1-netconfig?timeout=10s)": no endpoints available for service "infra-operator-controller-manager-service"
```

Let' recheck it

**Comment by stuggi** [comment]
in the meantime this was fixed as part of https://github.com/openstack-k8s-operators/openstack-operator/commit/aa9196a5b8884ef0f8a3368fe933f6faf373d2e4

**Comment by slagle** [comment]
> in the meantime this was fixed as part of [aa9196a](https://github.com/openstack-k8s-operators/openstack-operator/commit/aa9196a5b8884ef0f8a3368fe933f6faf373d2e4)

ACK.

**Pull request closed without merging**
