### PR TITLE
Fix typo in mariadb templates

### PR DESCRIPTION
**Pull request by kajinamit**
The spec.mariadb.template does not exist and it should be spec.mariadb.template"s".

### CODE REVIEW

**Review by abays — APPROVED** [review]
/lgtm

**Comment by kajinamit** [comment]
recheck

**Comment by kajinamit** [comment]
recheck

looks like auth expired in the middle of the deployment job ?

**Comment by rabi** [comment]
recheck

**Comment by kajinamit** [comment]
I don't know why zuul job fails with merge conflict (I could rebase the change without any conflict)...

**Comment by abays** [comment]
I'm just going to merge this.  We need this fix to unblock other PRs.

**Pull request merged**
