### PR TITLE
Bump OSBMO to bump BMO to v0.6

### PR DESCRIPTION
**Pull request by abays**
Final step to begin using Metal3 v0.6

Depends-On: https://github.com/openstack-k8s-operators/openstack-baremetal-operator/pull/216

### CODE REVIEW

**Review by fao89 — APPROVED** [review]

**Comment by rabi** [comment]
`TASK [telemetry_adoption : deploy podified Ceilometer] *************************
fatal: [localhost]: FAILED! => {"changed": true, "cmd": "set -euxo pipefail\n\n\noc patch openstackcontrolplane openstack --type=merge --patch 'spec:\n  telemetry:\n    enabled: true\n    template:\n      ceilometer:\n        passwordSelector:\n          ceilometerService: CeilometerPassword\n        enabled: true\n        secret: osp-secret\n        serviceUser: ceilometer\n'\n", "delta": "0:00:00.238401", "end": "2024-10-02 11:37:50.633861", "msg": "non-zero return code", "rc": 1, "start": "2024-10-02 11:37:50.395460", "stderr": "+ oc patch openstackcontrolplane openstack --type=merge --patch 'spec:\n  telemetry:\n    enabled: true\n    template:\n      ceilometer:\n        passwordSelector:\n          ceilometerService: CeilometerPassword\n        enabled: true\n        secret: osp-secret\n        serviceUser: ceilometer\n'\nError from server (InternalError): Internal error occurred: failed calling webhook \"mopenstackcontrolplane.kb.io\": failed to call webhook: Post \"https://openstack-operator-controller-manager-service.openstack-operators.svc:443/mutate-core-openstack-org-v1beta1-openstackcontrolplane?timeout=10s\": no endpoints available for service \"openstack-operator-controller-manager-service\"", "stderr_lines": ["+ oc patch openstackcontrolplane openstack --type=merge --patch 'spec:", "  telemetry:", "    enabled: true", "    template:", "      ceilometer:", "        passwordSelector:", "          ceilometerService: CeilometerPassword", "        enabled: true", "        secret: osp-secret", "        serviceUser: ceilometer", "'", "Error from server (InternalError): Internal error occurred: failed calling webhook \"mopenstackcontrolplane.kb.io\": failed to call webhook: Post \"https://openstack-operator-controller-manager-service.openstack-operators.svc:443/mutate-core-openstack-org-v1beta1-openstackcontrolplane?timeout=10s\": no endpoints available for service \"openstack-operator-controller-manager-service\""], "stdout": "", "stdout_lines": []}`

**Comment by rabi** [comment]
recheck

**Comment by jpodivin** [comment]
Prow has one of those days :/ 

/test openstack-operator-build-deploy-kuttl

**Comment by abays** [comment]
> @abays: The following test **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:
> Test name 	Commit 	Details 	Required 	Rerun command
> ci/prow/openstack-operator-build-deploy-kuttl 	[44bae89](https://github.com/openstack-k8s-operators/openstack-operator/commit/44bae8976b48db6990c853ca8f73e22e12128e44) 	[link](https://prow.ci.openshift.org/view/gs/test-platform-results/pr-logs/pull/openstack-k8s-operators_openstack-operator/1114/pull-ci-openstack-k8s-operators-openstack-operator-main-openstack-operator-build-deploy-kuttl/1842108559383334912) 	true 	`/test openstack-operator-build-deploy-kuttl`
> 
> [Full PR test history](https://prow.ci.openshift.org/pr-history?org=openstack-k8s-operators&repo=openstack-operator&pr=1114). [Your PR dashboard](https://prow.ci.openshift.org/pr?query=is:pr+state:open+author:abays).

I doubt the KUTTL failure has anything to do with this patch:

```
--- FAIL: kuttl (857.38s)
    --- FAIL: kuttl/harness (0.00s)
        --- FAIL: kuttl/harness/ctlplane-tls-custom-issuers (855.26s)
```

/test openstack-operator-build-deploy-kuttl

**Pull request merged**
