### PR TITLE
Revert "Bump kustomize"

### PR DESCRIPTION
**Pull request by dprince**
This reverts commit a0eb7c30553f9a25b11f33fc5fc509a813179afc.

### CODE REVIEW

**Review by abays — APPROVED** [review]
/lgtm

**Comment by dprince** [comment]
The reverted commit breaks the openstack-operators CSV in that ENV variables are no longer merged correctly.

**Review by fao89 — APPROVED** [review]

**Comment by fao89** [comment]
should I revert it in dataplane-operator also?

**Comment by dprince** [comment]
@fao89 I haven't checked dataplane-operator yet. So long as the bundle still has images set we should be okay. Need to look into why this caused the issue here as well.

**Comment by abays** [comment]
recheck

**Pull request merged**
