### PR TITLE
Add Heat operator to OpenStackControlPlane

### PR DESCRIPTION
**Pull request by bshephar**
This change adds the Heat operator to the OpenStackControlPlane. This is disabled by default and will need to be explicitly enabled.

### CODE REVIEW

**Comment by abays** [comment]
This was failing to due bundle size issues:

```
2023-05-25T00:21:05.000970401Z E0525 00:21:05.000879       1 queueinformer_operator.go:290] sync {"update" "openstack/install-wldwn"} failed: failed to update installplan bundle lookups: etcdserver: request is too large
```

But https://github.com/openstack-k8s-operators/openstack-operator/pull/324 has merged now, which should fix the problem.  Retesting.

/test openstack-operator-build-deploy

**Comment by bshephar** [comment]
Seems like this has still got the same error:
```
2023-05-25T14:59:32.088531715Z E0525 14:59:32.088458       1 queueinformer_operator.go:290] sync {"update" "openstack/install-2j7qb"} failed: failed to update installplan bundle lookups: etcdserver: request is too large
```

https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/pr-logs/pull/openstack-k8s-operators_openstack-operator/321/pull-ci-openstack-k8s-operators-openstack-operator-main-openstack-operator-build-deploy/1661743392469553152/artifacts/openstack-operator-build-deploy/openstack-k8s-operators-gather/artifacts/must-gather/quay-io-openshift-release-dev-ocp-v4-0-art-dev-sha256-6eac618c70508e7c135084b46d87f2a293ed5ea9d4ca616280f0663afb1a3e77/namespaces/openshift-operator-lifecycle-manager/pods/catalog-operator-595d4787cd-hltzm/catalog-operator/catalog-operator/logs/current.log

**Comment by bshephar** [comment]
Maybe the addition of Heat now also pushes it over the size limit.

**Review by dprince — APPROVED** [review]

**Pull request merged**
