### PR TITLE
[tempest] skip test_live_block_migration_with_attached_volume

### PR DESCRIPTION
**Pull request by stuggi**
no c-v configured yet

### CODE REVIEW

**Comment by stuggi** [comment]
test failed in https://github.com/openstack-k8s-operators/openstack-operator/pull/706 , https://github.com/openstack-k8s-operators/openstack-operator/pull/695 and https://github.com/openstack-k8s-operators/openstack-operator/pull/657 . it was automatically skipped in https://github.com/openstack-k8s-operators/openstack-operator/pull/705

**Review by gibizer — APPROVED** [review]

**Comment by stuggi** [comment]
`* 0001-01-01T00:00:00Z 0x : 0/27 nodes are available: 1 Insufficient cpu, 1 node(s) had untolerated taint {node-role.kubernetes.io/ci-longtests-worker: ci-longtests-worker}, 2 node(s) had untolerated taint {node-role.kubernetes.io/infra: }, 3 node(s) had untolerated taint {node-role.kubernetes.io/master: }, 5 node(s) didn't match Pod's node affinity/selector, 6 node(s) had untolerated taint {node-role.kubernetes.io/ci-prowjobs-worker: ci-prowjobs-worker}, 9 node(s) had untolerated taint {node-role.kubernetes.io/ci-tests-worker: ci-tests-worker}. preemption: 0/27 nodes are available: 1 No preemption victims found for incoming pod, 26 Preemption is not helpful for scheduling.`

**Pull request merged**
