### PR TITLE
Update telemetry.autoscaling in sample CRs

### PR DESCRIPTION
**Pull request by vyzigold**

### CODE REVIEW

**Comment by vyzigold** [comment]
recheck
retry limit

**Comment by vyzigold** [comment]
recheck

**Comment by vyzigold** [comment]
recheck
Failure installing cert-manager
```
TASK [cert_manager : Install cert-manager cmctl CLI src=[https://github.com/cert-manager/cert-manager/releases/{{](https://github.com/cert-manager/cert-manager/releases/%7B%7B) cifmw_cert_manager_version }}/download/cmctl-linux-amd64.tar.gz, dest={{ lookup('env', 'HOME') }}/bin/, remote_src=True] ***
Thursday 25 April 2024  13:31:23 -0400 (0:00:00.284)       0:03:29.755 ******** 
fatal: [localhost]: FAILED! => {"changed": false, "msg": "Invalid archive '/home/zuul/.ansible/tmp/ansible-tmp-1714066283.736121-11731-172477245010155/cmctl-linux-amd64bgixioth.tar.gz', the file is 0 bytes"}
```

**Review by stuggi — APPROVED** [review]
/lgtm

**Pull request merged**
