### PR TITLE
Bump to latest dataplane-operator

### PR DESCRIPTION
**Pull request by dprince**
go get github.com/openstack-k8s-operators/dataplane-operator/api@main

### CODE REVIEW

**Review by abays — APPROVED** [review]
/lgtm

**Comment by fao89** [comment]
recheck

**Comment by abays** [comment]
recheck

**Comment by pablintino** [comment]
@abays as usual, the refresh of the crc image broke CI... We are working on it

**Comment by rabi** [comment]
@abays we should merge https://github.com/openstack-k8s-operators/openstack-operator/pull/485 instead which would also bump dataplane-operator after the multinode edpm job has been fixed.

**Comment by abays** [comment]
> @abays we should merge #485 instead which would also bump dataplane-operator after the multinode edpm job has been fixed.

Okay, once the job is fixed let's try to merge the other one

**Comment by dprince** [comment]
looks like a renovate PR bump landed so I think this is no longer needed

**Pull request closed without merging**
