### PR TITLE
follow up of a518f8fb3aa1d4dfc20fa24d9bfcbf0a5afacc31 to fix ironic

### PR DESCRIPTION
**Pull request by stuggi**

### CODE REVIEW

**Review by abays — APPROVED** [review]
/lgtm

**Review by hjensas — APPROVED** [review]
Thanks Martin!

**Comment by hjensas** [comment]
recheck

Should work with https://github.com/openstack-k8s-operators/dataplane-operator/pull/741 ?

**Comment by hjensas** [comment]
recheck

**Pull request merged**
