### PR TITLE
Bump the rabbitmq operator pin to the latest

### PR DESCRIPTION
**Pull request by dprince**

### CODE REVIEW

**Comment by gibizer** [comment]
/test openstack-operator-build-deploy-kuttl

```
+ git clone https://github.com/openstack-k8s-operators/install_yamls.git
Cloning into 'install_yamls'...
error: RPC failed; HTTP 500 curl 22 The requested URL returned error: 500
```

**Comment by gibizer** [comment]
/test openstack-operator-build-deploy-kuttl

I'm not sure why we failed the kuttl test but at least the deployment was OK so I think the bump itself is good we just have unstable CI 
```
=== RUN   kuttl/harness
=== RUN   kuttl/harness/basic-deployment
=== PAUSE kuttl/harness/basic-deployment
=== RUN   kuttl/harness/collapsed
=== PAUSE kuttl/harness/collapsed
=== RUN   kuttl/harness/galera-3replicas
=== PAUSE kuttl/harness/galera-3replicas
=== CONT  kuttl/harness/basic-deployment
    logger.go:42: 14:04:16 | basic-deployment | Skipping creation of user-supplied namespace: openstack-kuttl-tests
    logger.go:42: 14:04:16 | basic-deployment/1-deploy-openstack | starting test step 1-deploy-openstack
    logger.go:42: 14:04:16 | basic-deployment/1-deploy-openstack | running command: [sh -c oc apply -n $NAMESPACE -f ../../../../config/samples/core_v1beta1_openstackcontrolplane.yaml
        ]
    logger.go:42: 14:04:16 | basic-deployment/1-deploy-openstack | openstackcontrolplane.core.openstack.org/openstack created
    logger.go:42: 14:13:15 | basic-deployment/1-deploy-openstack | test step completed 1-deploy-openstack
    logger.go:42: 14:13:15 | basic-deployment/2-cleanup | starting test step 2-cleanup
I0721 14:13:16.423419    3781 request.go:682] Waited for 1.025771938s due to client-side throttling, not priority and fairness, request: GET:https://api.oko-11.oooci.ccitredhat.com:6443/apis/whereabouts.cni.cncf.io/v1alpha1?timeout=32s
    logger.go:42: 14:13:19 | basic-deployment/2-cleanup | test step completed 2-cleanup
    logger.go:42: 14:13:19 | basic-deployment | skipping kubernetes event logging
=== CONT  kuttl/harness/galera-3replicas
    logger.go:42: 14:13:19 | galera-3replicas | Skipping creation of user-supplied namespace: openstack-kuttl-tests
    logger.go:42: 14:13:19 | galera-3replicas/1-deploy-galera-3replicas | starting test step 1-deploy-galera-3replicas
    logger.go:42: 14:13:19 | galera-3replicas/1-deploy-galera-3replicas | running command: [sh -c oc apply -n $NAMESPACE -f ../../../../config/samples/core_v1beta1_openstackcontrolplane_galera_3replicas.yaml
        ]
    logger.go:42: 14:13:20 | galera-3replicas/1-deploy-galera-3replicas | openstackcontrolplane.core.openstack.org/openstack created
    logger.go:42: 14:13:24 | galera-3replicas/1-deploy-galera-3replicas | test step completed 1-deploy-galera-3replicas
    logger.go:42: 14:13:24 | galera-3replicas/2-cleanup | starting test step 2-cleanup
    logger.go:42: 14:13:24 | galera-3replicas/2-cleanup | running command: [sh -c oc delete --ignore-not-found=true -n $NAMESPACE pvc \
        mysql-db-openstack-galera-0 \
        mysql-db-openstack-galera-1 \
        mysql-db-openstack-galera-2 \
        mysql-db-openstack-cell1-galera-0 \
        mysql-db-openstack-cell1-galera-1 \
        mysql-db-openstack-cell1-galera-2 \
        srv-swift-storage-0
        ]
    logger.go:42: 14:13:25 | galera-3replicas/2-cleanup | persistentvolumeclaim "mysql-db-openstack-galera-0" deleted
    logger.go:42: 14:13:25 | galera-3replicas/2-cleanup | persistentvolumeclaim "mysql-db-openstack-galera-1" deleted
    logger.go:42: 14:13:25 | galera-3replicas/2-cleanup | persistentvolumeclaim "mysql-db-openstack-galera-2" deleted
    logger.go:42: 14:13:26 | galera-3replicas/2-cleanup | persistentvolumeclaim "srv-swift-storage-0" deleted
I0721 14:30:06.219125    3781 request.go:682] Waited for 1.049366016s due to client-side throttling, not priority and fairness, request: GET:https://api.oko-11.oooci.ccitredhat.com:6443/apis/monitoring.coreos.com/v1alpha1?timeout=32s
    case.go:364: failed in step 2-cleanup
    case.go:366: command "" exceeded 1000 sec timeout, context deadline exceeded
    logger.go:42: 14:30:08 | galera-3replicas | skipping kubernetes event logging
=== CONT  kuttl/harness/collapsed
    logger.go:42: 14:30:08 | collapsed | Skipping creation of user-supplied namespace: openstack-kuttl-tests
    logger.go:42: 14:30:08 | collapsed/1-deploy-openstack-collapsed-cell | starting test step 1-deploy-openstack-collapsed-cell
    logger.go:42: 14:30:08 | collapsed/1-deploy-openstack-collapsed-cell | running command: [sh -c oc apply -n $NAMESPACE -f ../../../../config/samples/core_v1beta1_openstackcontrolplane_collapsed_cell.yaml
        ]
    logger.go:42: 14:30:09 | collapsed/1-deploy-openstack-collapsed-cell | openstackcontrolplane.core.openstack.org/openstack-collapsed-cell created
    logger.go:42: 14:30:13 | collapsed/1-deploy-openstack-collapsed-cell | test step completed 1-deploy-openstack-collapsed-cell
    logger.go:42: 14:30:13 | collapsed/2-cleanup | starting test step 2-cleanup
I0721 14:30:16.266290    3781 request.go:682] Waited for 2.886157356s due to client-side throttling, not priority and fairness, request: GET:https://api.oko-11.oooci.ccitredhat.com:6443/apis/user.openshift.io/v1?timeout=32s
    logger.go:42: 14:30:16 | collapsed/2-cleanup | test step completed 2-cleanup
    logger.go:42: 14:30:16 | collapsed | skipping kubernetes event logging
=== CONT  kuttl
    harness.go:405: run tests finished
    harness.go:513: cleaning up
    harness.go:570: removing temp folder: ""
--- FAIL: kuttl (1572.14s)
    --- FAIL: kuttl/harness (0.00s)
        --- PASS: kuttl/harness/basic-deployment (543.59s)
        --- FAIL: kuttl/harness/galera-3replicas (1008.99s)
        --- PASS: kuttl/harness/collapsed (8.31s)
FAIL
```

**Comment by abays** [comment]
> /test openstack-operator-build-deploy-kuttl
> 
> I'm not sure why we failed the kuttl test but at least the deployment was OK so I think the bump itself is good we just have unstable CI
> 
> ```
> === RUN   kuttl/harness
> === RUN   kuttl/harness/basic-deployment
> === PAUSE kuttl/harness/basic-deployment
> === RUN   kuttl/harness/collapsed
> === PAUSE kuttl/harness/collapsed
> === RUN   kuttl/harness/galera-3replicas
> === PAUSE kuttl/harness/galera-3replicas
> === CONT  kuttl/harness/basic-deployment
>     logger.go:42: 14:04:16 | basic-deployment | Skipping creation of user-supplied namespace: openstack-kuttl-tests
>     logger.go:42: 14:04:16 | basic-deployment/1-deploy-openstack | starting test step 1-deploy-openstack
>     logger.go:42: 14:04:16 | basic-deployment/1-deploy-openstack | running command: [sh -c oc apply -n $NAMESPACE -f ../../../../config/samples/core_v1beta1_openstackcontrolplane.yaml
>         ]
>     logger.go:42: 14:04:16 | basic-deployment/1-deploy-openstack | openstackcontrolplane.core.openstack.org/openstack created
>     logger.go:42: 14:13:15 | basic-deployment/1-deploy-openstack | test step completed 1-deploy-openstack
>     logger.go:42: 14:13:15 | basic-deployment/2-cleanup | starting test step 2-cleanup
> I0721 14:13:16.423419    3781 request.go:682] Waited for 1.025771938s due to client-side throttling, not priority and fairness, request: GET:https://api.oko-11.oooci.ccitredhat.com:6443/apis/whereabouts.cni.cncf.io/v1alpha1?timeout=32s
>     logger.go:42: 14:13:19 | basic-deployment/2-cleanup | test step completed 2-cleanup
>     logger.go:42: 14:13:19 | basic-deployment | skipping kubernetes event logging
> === CONT  kuttl/harness/galera-3replicas
>     logger.go:42: 14:13:19 | galera-3replicas | Skipping creation of user-supplied namespace: openstack-kuttl-tests
>     logger.go:42: 14:13:19 | galera-3replicas/1-deploy-galera-3replicas | starting test step 1-deploy-galera-3replicas
>     logger.go:42: 14:13:19 | galera-3replicas/1-deploy-galera-3replicas | running command: [sh -c oc apply -n $NAMESPACE -f ../../../../config/samples/core_v1beta1_openstackcontrolplane_galera_3replicas.yaml
>         ]
>     logger.go:42: 14:13:20 | galera-3replicas/1-deploy-galera-3replicas | openstackcontrolplane.core.openstack.org/openstack created
>     logger.go:42: 14:13:24 | galera-3replicas/1-deploy-galera-3replicas | test step completed 1-deploy-galera-3replicas
>     logger.go:42: 14:13:24 | galera-3replicas/2-cleanup | starting test step 2-cleanup
>     logger.go:42: 14:13:24 | galera-3replicas/2-cleanup | running command: [sh -c oc delete --ignore-not-found=true -n $NAMESPACE pvc \
>         mysql-db-openstack-galera-0 \
>         mysql-db-openstack-galera-1 \
>         mysql-db-openstack-galera-2 \
>         mysql-db-openstack-cell1-galera-0 \
>         mysql-db-openstack-cell1-galera-1 \
>         mysql-db-openstack-cell1-galera-2 \
>         srv-swift-storage-0
>         ]
>     logger.go:42: 14:13:25 | galera-3replicas/2-cleanup | persistentvolumeclaim "mysql-db-openstack-galera-0" deleted
>     logger.go:42: 14:13:25 | galera-3replicas/2-cleanup | persistentvolumeclaim "mysql-db-openstack-galera-1" deleted
>     logger.go:42: 14:13:25 | galera-3replicas/2-cleanup | persistentvolumeclaim "mysql-db-openstack-galera-2" deleted
>     logger.go:42: 14:13:26 | galera-3replicas/2-cleanup | persistentvolumeclaim "srv-swift-storage-0" deleted
> I0721 14:30:06.219125    3781 request.go:682] Waited for 1.049366016s due to client-side throttling, not priority and fairness, request: GET:https://api.oko-11.oooci.ccitredhat.com:6443/apis/monitoring.coreos.com/v1alpha1?timeout=32s
>     case.go:364: failed in step 2-cleanup
>     case.go:366: command "" exceeded 1000 sec timeout, context deadline exceeded
>     logger.go:42: 14:30:08 | galera-3replicas | skipping kubernetes event logging
> === CONT  kuttl/harness/collapsed
>     logger.go:42: 14:30:08 | collapsed | Skipping creation of user-supplied namespace: openstack-kuttl-tests
>     logger.go:42: 14:30:08 | collapsed/1-deploy-openstack-collapsed-cell | starting test step 1-deploy-openstack-collapsed-cell
>     logger.go:42: 14:30:08 | collapsed/1-deploy-openstack-collapsed-cell | running command: [sh -c oc apply -n $NAMESPACE -f ../../../../config/samples/core_v1beta1_openstackcontrolplane_collapsed_cell.yaml
>         ]
>     logger.go:42: 14:30:09 | collapsed/1-deploy-openstack-collapsed-cell | openstackcontrolplane.core.openstack.org/openstack-collapsed-cell created
>     logger.go:42: 14:30:13 | collapsed/1-deploy-openstack-collapsed-cell | test step completed 1-deploy-openstack-collapsed-cell
>     logger.go:42: 14:30:13 | collapsed/2-cleanup | starting test step 2-cleanup
> I0721 14:30:16.266290    3781 request.go:682] Waited for 2.886157356s due to client-side throttling, not priority and fairness, request: GET:https://api.oko-11.oooci.ccitredhat.com:6443/apis/user.openshift.io/v1?timeout=32s
>     logger.go:42: 14:30:16 | collapsed/2-cleanup | test step completed 2-cleanup
>     logger.go:42: 14:30:16 | collapsed | skipping kubernetes event logging
> === CONT  kuttl
>     harness.go:405: run tests finished
>     harness.go:513: cleaning up
>     harness.go:570: removing temp folder: ""
> --- FAIL: kuttl (1572.14s)
>     --- FAIL: kuttl/harness (0.00s)
>         --- PASS: kuttl/harness/basic-deployment (543.59s)
>         --- FAIL: kuttl/harness/galera-3replicas (1008.99s)
>         --- PASS: kuttl/harness/collapsed (8.31s)
> FAIL
> ```

Agreed.  @jparoly is working to better stabilize these tests.  I think it is safe to override this check for this PR.

**Comment by dprince** [comment]
error looks like it failed to run must-gather after the kuttl tests. going to retry it again

**Comment by dprince** [comment]
Using the latest bump I'm seeing the following failure when launching the rabbitmq-cell1-server-0 pod:

  Warning  FailedMount  3m5s                kubelet            Unable to attach or mount volumes: unmounted volumes=[persistence], unattached volumes=[pod-info plugins-conf rabbitmq-erlang-cookie erlang-cookie-secret rabbitmq-plugins persistence rabbitmq-confd kube-api-access-qmfbg]: timed out waiting for the condition

I think this is the cause of the kuttl tests now

**Comment by dprince** [comment]
> Using the latest bump I'm seeing the following failure when launching the rabbitmq-cell1-server-0 pod:
> 
> Warning FailedMount 3m5s kubelet Unable to attach or mount volumes: unmounted volumes=[persistence], unattached volumes=[pod-info plugins-conf rabbitmq-erlang-cookie erlang-cookie-secret rabbitmq-plugins persistence rabbitmq-confd kube-api-access-qmfbg]: timed out waiting for the condition
> 
> I think this is the cause of the kuttl tests now

scratch that. Local testing error on my part. Trying again.

**Comment by dprince** [comment]
and its passing CI, so great news

**Review by abays — APPROVED** [review]
/lgtm

**Pull request merged**
