### PR TITLE
Bump dataplane-operator

### PR DESCRIPTION
**Pull request by rabi**
Depends-On: https://github.com/openstack-k8s-operators/data-plane-adoption/pull/253
Depends-On: https://github.com/openstack-k8s-operators/ci-framework/pull/1063

### CODE REVIEW

**Comment by rabi** [comment]
recheck

**Comment by rabi** [comment]
recheck

**Comment by rabi** [comment]
recheck kernel panic

**Comment by rabi** [comment]
recheck RETRY_LIMIT

**Review by bshephar — APPROVED** [review]

**Comment by rabi** [comment]
recheck kernel panic

**Review by jistr — APPROVED** [review]

**Comment by cjeanner** [comment]
recheck

**Comment by pablintino** [comment]
recheck

**Comment by karelyatin** [comment]
recheck unrelated failures

**Comment by pablintino** [comment]
recheck

**Comment by cjeanner** [comment]
@pablintino proposal: last recheck? the expected job did pass, so imho if the next one is also seeing a CRC crash (that's the issue with the tempest job), we should discard zuul and get the patch in. This will unlock other PRs and, hopefully, alleviate the pressure we have on our team - and give us some more time to properly debug the crc crashes.

@rabi OK for you?

**Comment by cjeanner** [comment]
recheck

unwanted crash due to depends-on update

**Comment by cjeanner** [comment]
recheck

**Pull request merged**
