### PR TITLE
OpenStackVersion: ensure there is only one

### PR DESCRIPTION
**Pull request by dprince**
Jira: [OSPRH-6874](https://issues.redhat.com//browse/OSPRH-6874)

### CODE REVIEW

**Comment by abays** [comment]
recheck

**Comment by karelyatin** [comment]
> recheck

there is a real issue so would need the fix https://github.com/openstack-k8s-operators/openstack-operator/pull/825

**Comment by fao89** [comment]
recheck

**Review by fao89 — APPROVED** [review]

**Pull request merged**
