### PR TITLE
Drop csv merger

### PR DESCRIPTION
**Pull request by dprince**
With this change the RELATED_IMAGES for all service operators are all listed (and ordered) with the openstack-operators. Use of the csv_merger is dropped and bundle generation is greatly simplified as a result.

### CODE REVIEW

**Comment by yazug** [comment]
This should help with OSPRH-8398

**Comment by yazug** [comment]
kuttle failing with the following, which appears to be the warnings I was seeing before with duplicate related images mapping to the same image and having weird naming or empty name

 time="2024-07-11T17:54:33Z" level=fatal msg="Error generating bundle manifests: failed to set related images: bundle/manifests/openstack-operator.clusterserviceversion.yaml - Found conflicts when setting relatedImages:\nrelatedImage : quay.io/podified-antelope-centos9/openstack-aodh-api@sha256:7cdfa816e5228fa4ef2e68989f1ecfb8eea2c0930897bda222f6f3d387a6548f X relatedImage : registry.redhat.io/ubi9/httpd-24@sha256:7830b8d73168bcdec441141392bbfd4f3e4c7715bc0cefd3d9ef456767608917\nrelatedImage : quay.io/podified-antelope-centos9/openstack-aodh-api@sha256:7cdfa816e5228fa4ef2e68989f1ecfb8eea2c0930897bda222f6f3d387a6548f X relatedImage : quay.io/podified-antelope-centos9/openstack-ovn-controller@sha256:1930e5f63a0ad8b35d3038537f649c49a7669d75271c4d89c629f429db518305\nrelatedImage : quay.io/podified-antelope-centos9/openstack-aodh-api@sha256:7cdfa816e5228fa4ef2e68989f1ecfb8eea2c0930897bda222f6f3d387a6548f X relatedImage : quay.io/podified-antelope-centos9/openstack-neutron-server@sha256:cc23ff0d2413d5fde5cb46a644d1523b9a97538d13c2328c2d76d6835f683879"

**Comment by dprince** [comment]
I was aware of the warnings, but didn't realize they would cause kuttle test errors.

@yazug this telemetry-operator PR should fix 2 of those errors: https://github.com/openstack-k8s-operators/telemetry-operator/pull/440 

I will look at the rest...

**Comment by dprince** [comment]
Trying to do this in parts isn't getting traction. I pushed the complete PR here: https://github.com/openstack-k8s-operators/openstack-operator/pull/1012

**Pull request closed without merging**
