### PR TITLE
Consider nodeset hash to update the completion status

### PR DESCRIPTION
**Pull request by fao89**
[OSPRH-8397](https://issues.redhat.com//browse/OSPRH-8397)

### CODE REVIEW

**Review by slagle — COMMENTED** [review]
+2

**Comment by fao89** [comment]
recheck

**Comment by pablintino** [comment]
I'm fine with it, tested against HCI. I'll run some extra runs be sure it fixes the issue, as it seems unpredictable, despite it showed up for me on each run I did.

**Review by jpodivin — APPROVED** [review]

**Comment by rabi** [comment]
LGTM, but where is the blocker jira for this? Are we not still in blocker-only mode?

**Comment by fao89** [comment]
> LGTM, but where is the blocker jira for this? Are we not still in blocker-only mode?

it was uncovered by OSPCIX-352 (the tempest starts to run before the nodeset being ready)

**Comment by rabi** [comment]
> > LGTM, but where is the blocker jira for this? Are we not still in blocker-only mode?
> 
> it was uncovered by [OSPCIX-352](https://issues.redhat.com//browse/OSPCIX-352) (tempest starts to run before the nodeset is ready)

I had looked at that. If one creates a new deployment after updating/patching the nodeset and then checks the nodeset status, they won't have the  issue. The issue in the workflow of that job is that we're checking the status before creating a deployment.

**Comment by rabi** [comment]
> rabi closed this now

Sorry clicked the wrong button.

**Comment by fao89** [comment]
actually, they check the status after the deployment: https://github.com/openstack-k8s-operators/architecture/blob/main/automation/vars/default.yaml#L73

```
2024-07-02 14:06:31,591 p=24790 u=zuul n=ansible | TASK [kustomize_deploy : Apply generated content for examples/va/hci/deployment _raw_params=oc apply -f {{ _cr }}] ***
2024-07-02 14:06:31,591 p=24790 u=zuul n=ansible | Tuesday 02 July 2024  14:06:31 -0400 (0:00:00.073)       0:42:23.561 ********** 
2024-07-02 14:06:32,072 p=24790 u=zuul n=ansible | changed: [localhost]
2024-07-02 14:06:32,093 p=24790 u=zuul n=ansible | TASK [kustomize_deploy : Run Wait Conditions for examples/va/hci/deployment _raw_params={{ wait_condition }}] ***
2024-07-02 14:06:32,094 p=24790 u=zuul n=ansible | Tuesday 02 July 2024  14:06:32 -0400 (0:00:00.502)       0:42:24.064 ********** 
2024-07-02 14:06:32,750 p=24790 u=zuul n=ansible | changed: [localhost] => (item=oc -n openstack wait osdpns openstack-edpm --for condition=Ready --timeout=40m)
2024-07-02 14:06:32,768 p=24790 u=zuul n=ansible | TASK [kustomize_deploy : Stop after applying CRs if requested msg=Failing on demand {{ cifmw_deploy_architecture_stopper }}] ***
2024-07-02 14:06:32,768 p=24790 u=zuul n=ansible | Tuesday 02 July 2024  14:06:32 -0400 (0:00:00.674)       0:42:24.738 ********** 
```
https://sf.hosted.upshift.rdu2.redhat.com/logs/96/96/f391b023cb2071c3bc2ce71538724400311d018e/check-gitlab-cee/ci-framework-baremetal-static-node-rhel9-va-hci/f1aa706/logs/controller-0/ci-framework-data/logs/ansible-edpm-deploy.log

**Comment by rabi** [comment]
> actually, they check the status after the deployment: https://github.com/openstack-k8s-operators/architecture/blob/main/automation/vars/default.yaml#L73

Then it could be they are checking too quickly before the nodeset could reconcile (after the event from deployment) or maybe the query[1] we're doing does not show the deployment as we're using an empty context (context.Background()).

[1] https://github.com/openstack-k8s-operators/openstack-operator/blob/main/controllers/dataplane/openstackdataplanenodeset_controller.go#L474

**Pull request merged**
