### PR TITLE
bump to golang 1.21 and k8s to 1.29

### PR DESCRIPTION
**Pull request by stuggi**
Jira: https://issues.redhat.com//browse/OSPRH-6501

### CODE REVIEW

**Comment by bshephar** [comment]
Seems to have been an issue with Telemetry here:
```❯ curl -s "https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/test-platform-results/pr-logs/pull/openstack-k8s-operators_openstack-operator/1075/pull-ci-openstack-k8s-operators-openstack-operator-main-openstack-operator-build-deploy-kuttl/1835695758297272320/artifacts/openstack-operator-build-deploy-kuttl/openstack-k8s-operators-gather/artifacts/must-gather/quay-io-openstack-k8s-operators-openstack-must-gather-sha256-3d1f620ae3617fbd6371f55aa948b34e9daf31a461d3c557cf1a7c2db38d0385/namespaces/openstack-kuttl-tests/crs/openstackcontrolplanes.core.openstack.org/openstack.yaml" | yq '.status.conditions[] | select(.status == False)'
lastTransitionTime: "2024-09-16T16:07:39Z"
message: OpenStackControlPlane Telemetry in progress
reason: Requested
severity: Info
status: "False"
type: Ready
lastTransitionTime: "2024-09-16T16:07:32Z"
message: OpenStackControlPlane Telemetry in progress
reason: Requested
severity: Info
status: "False"
type: OpenStackControlPlaneTelemetryReady
```

```
❯ curl -s "https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/test-platform-results/pr-logs/pull/openstack-k8s-operators_openstack-operator/1075/pull-ci-openstack-k8s-operators-openstack-operator-main-openstack-operator-build-deploy-kuttl/1835695758297272320/artifacts/openstack-operator-build-deploy-kuttl/openstack-k8s-operators-gather/artifacts/must-gather/quay-io-openstack-k8s-operators-openstack-must-gather-sha256-3d1f620ae3617fbd6371f55aa948b34e9daf31a461d3c557cf1a7c2db38d0385/namespaces/openstack-kuttl-tests/crs/telemetries.telemetry.openstack.org/telemetry.yaml" | yq '.status.conditions'
- lastTransitionTime: "2024-09-16T16:07:18Z"
  message: Deployment not started
  reason: Init
  status: Unknown
  type: Ready
- lastTransitionTime: "2024-09-16T16:07:18Z"
  message: Deployment not started
  reason: Init
  status: Unknown
  type: CeilometerReady
  ```
  
  But the operator does report that it reconciled it successfully:
  ```
  ❯ curl -s "https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/test-platform-results/pr-logs/pull/openstack-k8s-operators_openstack-operator/1075/pull-ci-openstack-k8s-operators-openstack-operator-main-openstack-operator-build-deploy-kuttl/1835695758297272320/artifacts/openstack-operator-build-deploy-kuttl/openstack-k8s-operators-gather/artifacts/must-gather/quay-io-openstack-k8s-operators-openstack-must-gather-sha256-3d1f620ae3617fbd6371f55aa948b34e9daf31a461d3c557cf1a7c2db38d0385/namespaces/openstack-operators/pods/telemetry-operator-controller-manager-7d78579cf7-4qb5f/logs/manager.log" | tail -n 1
2024-09-16T16:07:18Z    INFO    Controllers.Ceilometer  Reconciled Service successfully {"controller": "ceilometer", "controllerGroup": "telemetry.openstack.org", "controllerKind": "Ceilometer", "Ceilometer": {"name":"ceilometer","namespace":"openstack-kuttl-tests"}, "namespace": "openstack-kuttl-tests", "name": "ceilometer", "reconcileID": "79781000-6d9c-4261-9e74-84fc53e11372"}
  ```
  
  Let's re-run and see if this reproduces.

**Review by bshephar — APPROVED** [review]

**Review by dprince — APPROVED** [review]

**Comment by dprince** [comment]
recheck

**Comment by bshephar** [comment]
recheck

**Comment by stuggi** [comment]
rebased

**Comment by stuggi** [comment]
recheck

**Comment by stuggi** [comment]
recheck

**Comment by stuggi** [comment]
recheck

**Review by olliewalsh — APPROVED** [review]
/lgtm

**Comment by bshephar** [comment]
```
harness.go:278: Successful connection to cluster at: https://api.oko-08.oooci.ccitredhat.com:6443/
    logger.go:42: 18:28:34 |  | running command: [oc apply -n openstack-kuttl-tests -f https://raw.githubusercontent.com/openstack-k8s-operators/infra-operator/main/config/samples/network_v1beta1_netconfig.yaml]
    logger.go:42: 18:28:34 |  | Error from server (InternalError): error when creating "https://raw.githubusercontent.com/openstack-k8s-operators/infra-operator/main/config/samples/network_v1beta1_netconfig.yaml": Internal error occurred: failed calling webhook "mnetconfig.kb.io": failed to call webhook: Post "[https://infra-operator-controller-manager-service.openstack-operators.svc:443/mutate-network-openstack-org-v1beta1-netconfig?timeout=10s](https://infra-operator-controller-manager-service.openstack-operators.svc/mutate-network-openstack-org-v1beta1-netconfig?timeout=10s)": no endpoints available for service "infra-operator-controller-manager-service"
```

Let's recheck it

**Comment by stuggi** [comment]
rebased

**Comment by stuggi** [comment]
recheck

**Review by olliewalsh — APPROVED** [review]
/lgtm

**Pull request merged**
