### PR TITLE
[tempest]Reenable test_live_block_migration_paused

### PR DESCRIPTION
**Pull request by gibizer**
Upstream fixes merged https://review.opendev.org/q/topic:%22bug/1671011%22

### CODE REVIEW

**Comment by gibizer** [comment]
The re-enabled test passing now
```
test_live_block_migration_paused[id-1e107f21-61b2-4988-8f22-b196e938ab88,multinode]
	pass
```
The baremetal job failure is a known CI issue. So we need to wait.

**Comment by gibizer** [comment]
recheck

**Comment by gibizer** [comment]
recheck

**Comment by gibizer** [comment]
recheck

**Review by stuggi — APPROVED** [review]
/lgtm

**Pull request merged**
