### PR TITLE
OpenstackVersion: add save conditions logic

### PR DESCRIPTION
**Pull request by dprince**
without this there is a reconcile loop between
this resource and the controlplane

### CODE REVIEW

**Review by gibizer — APPROVED** [review]
Looks good. Should we add the same logic to the OpenStackControlPlane resource too?

**Review by fmount — APPROVED** [review]

**Comment by dprince** [comment]
> Looks good. Should we add the same logic to the OpenStackControlPlane resource too?

As discussed as slack I am already doing this. I pulled this out of my (in progress) PR as it is straightforward and causing issues.

**Comment by gibizer** [comment]
/test openstack-operator-build-deploy-kuttl
```
failed to wait for the created cluster claim to become ready: timed out waiting for the condition
```

**Comment by gibizer** [comment]
> > Looks good. Should we add the same logic to the OpenStackControlPlane resource too?
> 
> As discussed as slack I am already doing this. I pulled this out of my (in progress) PR as it is straightforward and causing issues.

based on my testing we do need the Save and restore logic in the OpenStackControlPlane controller to stop the looping

**Comment by gibizer** [comment]
> > > Looks good. Should we add the same logic to the OpenStackControlPlane resource too?
> > 
> > 
> > As discussed as slack I am already doing this. I pulled this out of my (in progress) PR as it is straightforward and causing issues.
> 
> based on my testing we do need the Save and restore logic in the OpenStackControlPlane controller to stop the looping

pushed in https://github.com/openstack-k8s-operators/openstack-operator/pull/750

**Pull request merged**
