### PR TITLE
Disable HTTP2 in webhooks

### PR DESCRIPTION
**Pull request by dprince**
Also bumps golang.org/x/net to v0.17.0

Jira: [OSPRH-468](https://issues.redhat.com//browse/OSPRH-468)

Depends-On: https://github.com/openstack-k8s-operators/openstack-ansibleee-operator/pull/264

### CODE REVIEW

**Review by abays — APPROVED** [review]
/lgtm

**Comment by stuggi** [comment]
recheck

**Comment by dprince** [comment]
recheck

**Comment by rebtoor** [comment]
recheck

added depends-on

**Comment by rebtoor** [comment]
recheck

**Pull request merged**
