### PR TITLE
openstack-ansibleee-operator version bump

### PR DESCRIPTION
**Pull request by rebtoor**
Needed to get latest edpm-ansible fixes

### CODE REVIEW

**Comment by viroel** [comment]
recheck

**Comment by viroel** [comment]
/override rdoproject.org/github-check

cifmw-data-plane-adoption-osp-17-to-extracted-crc  is failing across other repos[1], not related to this change itself. We need to override to get the libvirtd pin fix[2].
Also, edpm-multinode is using latest ansibleee-runner image[3]

[1] https://review.rdoproject.org/zuul/builds?job_name=cifmw-data-plane-adoption-osp-17-to-extracted-crc&project=openstack-k8s-operators/openstack-operator
[2] https://github.com/openstack-k8s-operators/edpm-ansible/pull/560
[3] https://logserver.rdoproject.org/63/663/d6e45caf1ad115a59920544d50b0a1723ec9663c/github-check/podified-multinode-edpm-deployment-crc/82283f7/controller/ci-framework-data/logs/openstack-k8s-operators-openstack-must-gather/namespaces/openstack/pods/configure-os-openstack-edpm-v5rnp/configure-os-openstack-edpm-v5rnp-describe

**Review by olliewalsh — APPROVED** [review]
/lgtm

**Pull request merged**
