### PR TITLE
Adds new curl url for docker.io in pin-bundle script

### PR DESCRIPTION
**Pull request by viroel**
Since we are facing issues with quay.rdoproject to push image from Prow CI, we plan to move jobs images to docker.io. To properly build the bundles we need to fix pin-bundle-images script to retrieve the proper tag.

### CODE REVIEW

**Comment by viroel** [comment]
Testing here: https://github.com/openshift/release/pull/47943

**Comment by dprince** [comment]
@viroel looks okay to me, merge when the tests look good

**Comment by viroel** [comment]
/recheck

issues don' t seems to be related. We may merge anyways to unblock other PRs

**Comment by viroel** [comment]
recheck

**Comment by viroel** [comment]
edpm failed with trying to get ovs running:
https://logserver.rdoproject.org/38/638/75227843c34660726d5e22d510ead67d0af49b98/github-check/cifmw-crc-podified-edpm-baremetal/9437360/ci-framework-data/logs/openstack-k8s-operators-openstack-must-gather/namespaces/openstack/pods/configure-network-openstack-edpm-ipam-955jq/logs/openstackansibleee.log

Not related to this patch.

**Comment by viroel** [comment]
Test results using docker.io as push regsitry:
Building:
https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/test-platform-results/pr-logs/pull/openshift_release/47943/rehearse-47943-pull-ci-openstack-k8s-operators-neutron-operator-main-neutron-operator-build-deploy/1749780002871709696/artifacts/neutron-operator-build-deploy/openstack-k8s-operators-build/build-log.txt
Deploying: 
https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/test-platform-results/pr-logs/pull/openshift_release/47943/rehearse-47943-pull-ci-openstack-k8s-operators-neutron-operator-main-neutron-operator-build-deploy/1749780002871709696/artifacts/neutron-operator-build-deploy/openstack-k8s-operators-deploy/build-log.txt
Deploying from docker:
`+ make openstack OPENSTACK_IMG=docker.io/rdotripleomirror/openstack-operator-index:10ba7e361d3b2660f720-1749780002871709696 NETWORK_ISOLATION=false`

**Comment by viroel** [comment]
Openstack-operator kuttl job passing with docker too:
https://prow.ci.openshift.org/view/gs/test-platform-results/pr-logs/pull/openshift_release/47943/rehearse-47943-pull-ci-openstack-k8s-operators-openstack-operator-main-openstack-operator-build-deploy-kuttl/1749783827561058304

**Pull request merged**
