### PR TITLE
Bump dataplane-operator in openstack-operator

### PR DESCRIPTION
**Pull request by rabi**
This would fix the broken edpm-baremetal job.

### CODE REVIEW

**Comment by rabi** [comment]
recheck

**Comment by rabi** [comment]
recheck

**Comment by abays** [comment]
Both the `openstack-operator-crc-podified-edpm-baremetal` and `openstack-operator-crc-podified-edpm-deployment` jobs passed independently across two runs.  I think we can override the Zuul check.

**Review by abays — APPROVED** [review]
/lgtm

**Pull request merged**
