### PR TITLE
Use correct secret for ceilometer ipmi agent

### PR DESCRIPTION
**Pull request by yadneshk**
Depends-On: openstack-k8s-operators/telemetry-operator#516

### CODE REVIEW

**Comment by abays** [comment]
Wouldn't this PR also need to update the `go.mod`s to use the latest Telemetry API, or has that already happened in an earlier PR here?

**Comment by yadneshk** [comment]
recheck

```
2024-10-22 14:24:52.542575 | fa163eb6-2ab0-4d70-a429-000000000068 |      FATAL | Run cephadm bootstrap | standalone.localdomain | error={"changed": true, "cmd": "/usr/sbin/cephadm --image registry.redhat.io/rhceph/rhceph-6-rhel9:latest \\bootstrap --yes-i-know --skip-firewalld --skip-prepare-host --ssh-private-key /home/ceph-
.
.
repo,install,registry-login,gather-facts,host-maintenance,agent,disk-rescan,sos}\n               ...\ncephadm: error: unrecognized arguments: --yes-i-know", "stderr_lines": ["usage: cephadm [-h] [--image IMAGE] [--docker] [--data-dir DATA_DIR]", "               [--log-dir LOG_DIR] [--logrotate-dir LOGROTATE_DIR]", "               [--sysctl-dir SYSCTL_DIR] [--unit-dir UNIT_DIR] [--verbose]", "               [--timeout TIMEOUT] [--retry RETRY] [--env ENV]", "               [--no-container-init] [--no-cgroups-split]", "               {version,pull,inspect-image,ls,list-networks,adopt,rm-daemon,rm-cluster,run,shell,enter,ceph-volume,zap-osds,unit,logs,bootstrap,deploy,_orch,check-host,prepare-host,add-repo,rm-repo,install,registry-login,gather-facts,host-maintenance,agent,disk-rescan,sos}", "               ...", "cephadm: error: unrecognized arguments: --yes-i-know"], "stdout": "", "stdout_lines": []}
```

**Comment by yadneshk** [comment]
recheck

**Comment by yadneshk** [comment]
recheck

```
Trying to pull registry.access.redhat.com/ubi9/go-toolset:1.21...
    Error: creating build container: initializing source docker://registry.access.redhat.com/ubi9/go-toolset:1.21: pinging container registry registry.access.redhat.com: Get "[https://registry.access.redhat.com/v2/":](https://registry.access.redhat.com/v2/%22:) dial tcp: lookup registry.access.redhat.com on 199.204.47.54:53: server misbehaving
    make: *** [Makefile:209: docker-build] Error 125
```

**Comment by yadneshk** [comment]
recheck

Now that https://github.com/openstack-k8s-operators/install_yamls/pull/937 is merged

**Review by abays — APPROVED** [review]
/lgtm

**Pull request merged**
