### PR TITLE
Updated versions for ansibleee and telemetry so the latter can trigge…

### PR DESCRIPTION
**Pull request by jlarriba**
…r the defaulting of the former

### CODE REVIEW

**Review by abays — APPROVED** [review]
/lgtm

**Comment by abays** [comment]
> @jlarriba: The following test **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:
> Test name 	Commit 	Details 	Required 	Rerun command
> ci/prow/openstack-operator-build-deploy 	[5da305c](https://github.com/openstack-k8s-operators/openstack-operator/commit/5da305cfa44d929244a866a651ad36ba9892e2e1) 	[link](https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openstack-k8s-operators_openstack-operator/341/pull-ci-openstack-k8s-operators-openstack-operator-main-openstack-operator-build-deploy/1666804937335508992) 	true 	`/test openstack-operator-build-deploy`
> 
> [Full PR test history](https://prow.ci.openshift.org/pr-history?org=openstack-k8s-operators&repo=openstack-operator&pr=341). [Your PR dashboard](https://prow.ci.openshift.org/pr?query=is:pr+state:open+author:jlarriba).

CI hiccup?

```
The connection to the server api.oko-09.oooci.ccitredhat.com:6443 was refused - did you specify the right host or port?
```

/test openstack-operator-build-deploy

**Comment by abays** [comment]
> @jlarriba: The following test **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:
> Test name 	Commit 	Details 	Required 	Rerun command
> ci/prow/openstack-operator-build-deploy 	[5da305c](https://github.com/openstack-k8s-operators/openstack-operator/commit/5da305cfa44d929244a866a651ad36ba9892e2e1) 	[link](https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openstack-k8s-operators_openstack-operator/341/pull-ci-openstack-k8s-operators-openstack-operator-main-openstack-operator-build-deploy/1666812240432467968) 	true 	`/test openstack-operator-build-deploy`
> 
> [Full PR test history](https://prow.ci.openshift.org/pr-history?org=openstack-k8s-operators&repo=openstack-operator&pr=341). [Your PR dashboard](https://prow.ci.openshift.org/pr?query=is:pr+state:open+author:jlarriba).

It looks like the Telemetry operator is missing a permission needed for the changes introduced by https://github.com/openstack-k8s-operators/telemetry-operator/pull/108:

```
[pod/telemetry-operator-controller-manager-f5f69dd85-hqlrh/manager] E0608 15:01:09.486869       1 reflector.go:140] pkg/mod/k8s.io/client-go@v0.26.3/tools/cache/reflector.go:169: Failed to watch *v1beta1.KeystoneAPI: failed to list *v1beta1.KeystoneAPI: keystoneapis.keystone.openstack.org is forbidden: User "system:serviceaccount:openstack-operators:telemetry-operator-controller-manager" cannot list resource "keystoneapis" in API group "keystone.openstack.org" at the cluster scope
```

**Comment by jlarriba** [comment]
Thank you very much, submitted the fix.

**Comment by jlarriba** [comment]
> @jlarriba: The following test **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:
> 
> Test name	Commit	Details	Required	Rerun command
> ci/prow/openstack-operator-build-deploy	[af6c59a](https://github.com/openstack-k8s-operators/openstack-operator/commit/af6c59a437e7bf8b6dd3f3e88a214231bc0a7cbd)	[link](https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openstack-k8s-operators_openstack-operator/341/pull-ci-openstack-k8s-operators-openstack-operator-main-openstack-operator-build-deploy/1666833664358486016)	true	`/test openstack-operator-build-deploy`
> [Full PR test history](https://prow.ci.openshift.org/pr-history?org=openstack-k8s-operators&repo=openstack-operator&pr=341). [Your PR dashboard](https://prow.ci.openshift.org/pr?query=is:pr+state:open+author:jlarriba).

I have been looking the job output for a while and I dont have a clue on what might be happening here.

**Comment by abays** [comment]
> > @jlarriba: The following test **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:
> > Test name	Commit	Details	Required	Rerun command
> > ci/prow/openstack-operator-build-deploy	[af6c59a](https://github.com/openstack-k8s-operators/openstack-operator/commit/af6c59a437e7bf8b6dd3f3e88a214231bc0a7cbd)	[link](https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openstack-k8s-operators_openstack-operator/341/pull-ci-openstack-k8s-operators-openstack-operator-main-openstack-operator-build-deploy/1666833664358486016)	true	`/test openstack-operator-build-deploy`
> > [Full PR test history](https://prow.ci.openshift.org/pr-history?org=openstack-k8s-operators&repo=openstack-operator&pr=341). [Your PR dashboard](https://prow.ci.openshift.org/pr?query=is:pr+state:open+author:jlarriba).
> 
> I have been looking the job output for a while and I dont have a clue on what might be happening here.

It seems like it's the same problem as before:

```
[pod/telemetry-operator-controller-manager-598874f6f4-hrg4j/manager] E0608 16:26:06.966202       1 reflector.go:140] pkg/mod/k8s.io/client-go@v0.26.3/tools/cache/reflector.go:169: Failed to watch *v1beta1.KeystoneAPI: failed to list *v1beta1.KeystoneAPI: keystoneapis.keystone.openstack.org is forbidden: User "system:serviceaccount:openstack-operators:telemetry-operator-controller-manager" cannot list resource "keystoneapis" in API group "keystone.openstack.org" at the cluster scope
```

**Comment by abays** [comment]
> > > @jlarriba: The following test **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:
> > > Test name	Commit	Details	Required	Rerun command
> > > ci/prow/openstack-operator-build-deploy	[af6c59a](https://github.com/openstack-k8s-operators/openstack-operator/commit/af6c59a437e7bf8b6dd3f3e88a214231bc0a7cbd)	[link](https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openstack-k8s-operators_openstack-operator/341/pull-ci-openstack-k8s-operators-openstack-operator-main-openstack-operator-build-deploy/1666833664358486016)	true	`/test openstack-operator-build-deploy`
> > > [Full PR test history](https://prow.ci.openshift.org/pr-history?org=openstack-k8s-operators&repo=openstack-operator&pr=341). [Your PR dashboard](https://prow.ci.openshift.org/pr?query=is:pr+state:open+author:jlarriba).
> > 
> > 
> > I have been looking the job output for a while and I dont have a clue on what might be happening here.
> 
> It seems like it's the same problem as before:
> 
> ```
> [pod/telemetry-operator-controller-manager-598874f6f4-hrg4j/manager] E0608 16:26:06.966202       1 reflector.go:140] pkg/mod/k8s.io/client-go@v0.26.3/tools/cache/reflector.go:169: Failed to watch *v1beta1.KeystoneAPI: failed to list *v1beta1.KeystoneAPI: keystoneapis.keystone.openstack.org is forbidden: User "system:serviceaccount:openstack-operators:telemetry-operator-controller-manager" cannot list resource "keystoneapis" in API group "keystone.openstack.org" at the cluster scope
> ```

The import of `telemetry-operator/api` needs to be bumped to at least: https://github.com/openstack-k8s-operators/telemetry-operator/commit/829eea76002d12834a9e6dec29918f0c04842646

**Comment by jlarriba** [comment]
> > > > @jlarriba: The following test **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:
> > > > Test name	Commit	Details	Required	Rerun command
> > > > ci/prow/openstack-operator-build-deploy	[af6c59a](https://github.com/openstack-k8s-operators/openstack-operator/commit/af6c59a437e7bf8b6dd3f3e88a214231bc0a7cbd)	[link](https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openstack-k8s-operators_openstack-operator/341/pull-ci-openstack-k8s-operators-openstack-operator-main-openstack-operator-build-deploy/1666833664358486016)	true	`/test openstack-operator-build-deploy`
> > > > [Full PR test history](https://prow.ci.openshift.org/pr-history?org=openstack-k8s-operators&repo=openstack-operator&pr=341). [Your PR dashboard](https://prow.ci.openshift.org/pr?query=is:pr+state:open+author:jlarriba).
> > > 
> > > 
> > > I have been looking the job output for a while and I dont have a clue on what might be happening here.
> > 
> > 
> > It seems like it's the same problem as before:
> > ```
> > [pod/telemetry-operator-controller-manager-598874f6f4-hrg4j/manager] E0608 16:26:06.966202       1 reflector.go:140] pkg/mod/k8s.io/client-go@v0.26.3/tools/cache/reflector.go:169: Failed to watch *v1beta1.KeystoneAPI: failed to list *v1beta1.KeystoneAPI: keystoneapis.keystone.openstack.org is forbidden: User "system:serviceaccount:openstack-operators:telemetry-operator-controller-manager" cannot list resource "keystoneapis" in API group "keystone.openstack.org" at the cluster scope
> > ```
> 
> The import of `telemetry-operator/api` needs to be bumped to at least: [openstack-k8s-operators/telemetry-operator@829eea7](https://github.com/openstack-k8s-operators/telemetry-operator/commit/829eea76002d12834a9e6dec29918f0c04842646)

I have pushed the update to the most recent commit.

Where do you see the log trace you are pasting here? It is not in "Details" of the CI job.

**Comment by abays** [comment]
Looks like `telemetry-operator/api` needs a bump again

**Comment by jlarriba** [comment]
Damn, I bumped and the forgot to add the files to the commit. I need the weekend.

**Review by fao89 — APPROVED** [review]

**Pull request merged**
