### PR TITLE
Replace Ceilometer's ProxyImage with a generic one to avoid duplicati…

### PR DESCRIPTION
**Pull request by jlarriba**
…on of related images

### CODE REVIEW

**Comment by jlarriba** [comment]
/hold

As discussed with Dan, I am not really comfortable of having Octavia and Telemetry sharing the same image, as that could mean that the image gets updated by one of the teams unkowingly to the other, and that can cause issues.

Sharing images is this going to be a pattern for all services?

**Comment by dprince** [comment]
> /hold
> 
> As discussed with Dan, I am not really comfortable of having Octavia and Telemetry sharing the same image, as that could mean that the image gets updated by one of the teams unkowingly to the other, and that can cause issues.
> 
> Sharing images is this going to be a pattern for all services?

My viewpoint on this is it is an Apache image (pretty basic service) so probably okay to share it right? And if down the road we need to isolate and have multiple settings referring to *different* container images so be it... we can.

One more detail, the HTTP image would actually get used in 3 places: baremetal-operator(the original reason we have it), telemetry-operator, and then octavia as well.

**Comment by dprince** [comment]
@jlarriba code here looks good. Aside from your question I am LGTM to merge this.

**Review by dprince — APPROVED** [review]

**Pull request merged**
