### PR TITLE
Bump openstack-baremetal-operator

### PR DESCRIPTION
**Pull request by rabi**

### CODE REVIEW

**Comment by rabi** [comment]
Rebased https://github.com/openstack-k8s-operators/openstack-operator/pull/627 and will close this if that one merges earlier.

**Comment by rabi** [comment]
recheck

**Comment by rabi** [comment]
> @rabi wondering what version of golang you are using locally? 

Hmm. Mine is 1.19.10, not sure how all those extra stuff got in in the PR. Locally I've only the changes to baremetal-operator entries it seems.

**Comment by karelyatin** [comment]
the other one https://github.com/openstack-k8s-operators/openstack-operator/pull/627 approved, so this no longer needed.

**Pull request closed without merging**
