### PR TITLE
Drop aee-operator dependency

### PR DESCRIPTION
**Pull request by fao89**
should we archive openstack-ansibleee-operator?

### CODE REVIEW

**Review by slagle — COMMENTED** [review]
this LGTM, but we could also include the cleanups in dependencies.yaml and CI_TOOLS_REPO/renovate.sh, and custom-bundle.Dockerfile.pinned

**Comment by fao89** [comment]
custom-bundle.Dockerfile was dropped: https://github.com/openstack-k8s-operators/openstack-operator/pull/1012
and here is the renovate change: https://github.com/openstack-k8s-operators/openstack-k8s-operators-ci/pull/110

**Comment by slagle** [comment]
> custom-bundle.Dockerfile was dropped: #1012 and here is the renovate change: [openstack-k8s-operators/openstack-k8s-operators-ci#110](https://github.com/openstack-k8s-operators/openstack-k8s-operators-ci/pull/110)

ok, stale file in my checkout :+1: 

what about dependencies.yaml?

**Review by slagle — APPROVED** [review]

**Pull request merged**
