### PR TITLE
Drop unnecessary labels from AEE job

### PR DESCRIPTION
**Pull request by rabi**
Depends-On: https://review.rdoproject.org/r/c/rdo-jobs/+/55212

### CODE REVIEW

**Review by bshephar — APPROVED** [review]
Nice, I like it.

**Comment by rabi** [comment]
`[Mon Oct 28 07:05:48.584548 2024] [wsgi:error] [pid 17:tid 64] [remote 10.217.0.2:46134] 2024-10-28 07:05:48.584 17 ERROR heat.common.wsgi [None req-cdec76cb-7f05-4439-b80d-0a9a30a508fb admin - - - - -] Unexpected error occurred serving API: Timed out waiting for a reply to message ID f5f23bd7595d4d1185ac6a61d1168f53: oslo_messaging.exceptions.MessagingTimeout: Timed out waiting for a reply to message ID f5f23bd7595d4d1185ac6a61d1168f53\x1b[00m
`

**Comment by rabi** [comment]
recheck

**Comment by rabi** [comment]
recheck

**Comment by bshephar** [comment]
Seems to be a mismatch on the nova secrets. Let's retest it to make sure it's consistent, I'm not sure how this change could be related.

**Pull request merged**
