### PR TITLE
Fix functional test and use new args in EnsureCert

### PR DESCRIPTION
**Pull request by vakwetu**
Depends-On: https://github.com/openstack-k8s-operators/lib-common/pull/386

### CODE REVIEW

**Comment by stuggi** [comment]
> Depends-On: [openstack-k8s-operators/lib-common#386](https://github.com/openstack-k8s-operators/lib-common/pull/386)

its merged now, need to bump go.mod

**Review by stuggi — APPROVED** [review]
/lgtm

**Comment by vakwetu** [comment]
recheck

**Pull request merged**
