### PR TITLE
Don't merge dataplane-operator bundle ENVs twice

### PR DESCRIPTION
**Pull request by dprince**

### CODE REVIEW

**Comment by abays** [comment]
> @dprince: The following test **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:
> Test name 	Commit 	Details 	Required 	Rerun command
> ci/prow/openstack-operator-build-deploy-kuttl 	[cfba4cc](https://github.com/openstack-k8s-operators/openstack-operator/commit/cfba4cc40d89667d3a638e6d00756ca5b33e9bcf) 	[link](https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openstack-k8s-operators_openstack-operator/480/pull-ci-openstack-k8s-operators-openstack-operator-main-openstack-operator-build-deploy-kuttl/1704954054137876480) 	true 	`/test openstack-operator-build-deploy-kuttl`
> 
> [Full PR test history](https://prow.ci.openshift.org/pr-history?org=openstack-k8s-operators&repo=openstack-operator&pr=480). [Your PR dashboard](https://prow.ci.openshift.org/pr?query=is:pr+state:open+author:dprince).

Not sure what to make of this error because I haven't dug into it, but here is the problem:

```
+ sed -i custom-bundle.Dockerfile.pinned -e 's|quay.io/openstack-k8s-operators/telemetry-operator-bundle.*|quay.io/openstack-k8s-operators/telemetry-operator-bundle:232275280f55f5e216912bafc8d949ed1fe132ef
232275280f55f5e216912bafc8d949ed1fe132ef|'
sed: -e expression #1, char 160: unterminated `s' command
make: *** [Makefile:233: bundle] Error 1
```

**Comment by dprince** [comment]
> > @dprince: The following test **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:
> > Test name 	Commit 	Details 	Required 	Rerun command
> > ci/prow/openstack-operator-build-deploy-kuttl 	[cfba4cc](https://github.com/openstack-k8s-operators/openstack-operator/commit/cfba4cc40d89667d3a638e6d00756ca5b33e9bcf) 	[link](https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openstack-k8s-operators_openstack-operator/480/pull-ci-openstack-k8s-operators-openstack-operator-main-openstack-operator-build-deploy-kuttl/1704954054137876480) 	true 	`/test openstack-operator-build-deploy-kuttl`
> > [Full PR test history](https://prow.ci.openshift.org/pr-history?org=openstack-k8s-operators&repo=openstack-operator&pr=480). [Your PR dashboard](https://prow.ci.openshift.org/pr?query=is:pr+state:open+author:dprince).
> 
> Not sure what to make of this error because I haven't dug into it, but here is the problem:
> 
> ```
> + sed -i custom-bundle.Dockerfile.pinned -e 's|quay.io/openstack-k8s-operators/telemetry-operator-bundle.*|quay.io/openstack-k8s-operators/telemetry-operator-bundle:232275280f55f5e216912bafc8d949ed1fe132ef
> 232275280f55f5e216912bafc8d949ed1fe132ef|'
> sed: -e expression #1, char 160: unterminated `s' command
> make: *** [Makefile:233: bundle] Error 1
> ```

That error is unrelated and should now be fixed.

**Comment by rabi** [comment]
recheck

**Pull request merged**
