### PR TITLE
DNM: test live migration

### PR DESCRIPTION
**Pull request by olliewalsh**
Depends-On: https://github.com/openstack-k8s-operators/edpm-ansible/pull/675

### CODE REVIEW

**Comment by olliewalsh** [comment]
recheck

**Comment by olliewalsh** [comment]
recheck

**Comment by olliewalsh** [comment]
recheck

**Comment by olliewalsh** [comment]
recheck

**Comment by olliewalsh** [comment]
recheck

**Comment by olliewalsh** [comment]
recheck

**Comment by olliewalsh** [comment]
recheck

**Comment by olliewalsh** [comment]
recheck

**Comment by olliewalsh** [comment]
recheck

**Comment by olliewalsh** [comment]
recheck

**Comment by stuggi** [comment]
@olliewalsh do we still need this, or can we close the PR?

**Comment by olliewalsh** [comment]
No longer needed

**Pull request closed without merging**
