### PR TITLE
Run functional tests in parallel

### PR DESCRIPTION
**Pull request by rabi**
It seems to take lot of time running locally.

### CODE REVIEW

**Review by fao89 — APPROVED** [review]

**Comment by rabi** [comment]
`logger.go:42: 09:04:01 |  | Error from server (InternalError): error when creating "https://raw.githubusercontent.com/openstack-k8s-operators/infra-operator/main/config/samples/network_v1beta1_netconfig.yaml": Internal error occurred: failed calling webhook "mnetconfig.kb.io": failed to call webhook: Post "[https://infra-operator-controller-manager-service.openstack-operators.svc:443/mutate-network-openstack-org-v1beta1-netconfig?timeout=10s](https://infra-operator-controller-manager-service.openstack-operators.svc/mutate-network-openstack-org-v1beta1-netconfig?timeout=10s)": no endpoints available for service "infra-operator-controller-manager-service"`

**Comment by abays** [comment]
> @rabi: The following test **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:
> Test name 	Commit 	Details 	Required 	Rerun command
> ci/prow/openstack-operator-build-deploy-kuttl 	[f0103e0](https://github.com/openstack-k8s-operators/openstack-operator/commit/f0103e09ca54c488f9e65f9b67f95313605d852b) 	[link](https://prow.ci.openshift.org/view/gs/test-platform-results/pr-logs/pull/openstack-k8s-operators_openstack-operator/1132/pull-ci-openstack-k8s-operators-openstack-operator-main-openstack-operator-build-deploy-kuttl/1845759581217624064) 	true 	`/test openstack-operator-build-deploy-kuttl`
> 
> [Full PR test history](https://prow.ci.openshift.org/pr-history?org=openstack-k8s-operators&repo=openstack-operator&pr=1132). [Your PR dashboard](https://prow.ci.openshift.org/pr?query=is:pr+state:open+author:rabi).

```
Failed to run 'make crc_storage_cleanup' target. Aborting
make[2]: *** [Makefile:596: crc_storage_cleanup_with_retries] Error 
```

/test openstack-operator-build-deploy-kuttl

**Pull request merged**
