### PR TITLE
Drop make-operator-lint from pre-commit

### PR DESCRIPTION
**Pull request by dprince**
This make target doesn't exist here

### CODE REVIEW

**Comment by dprince** [comment]
@gibizer didn't notice this was missing when I ran it locally. Trying to get the CI job working so just removing seemed easiest. But wanted to ask what is going on with "operator-lint" and should we use it in other operators aside from Nova eventually?

**Comment by gibizer** [comment]
> @gibizer didn't notice this was missing when I ran it locally. Trying to get the CI job working so just removing seemed easiest. But wanted to ask what is going on with "operator-lint" and should we use it in other operators aside from Nova eventually?

I'm confused. `operator-lint` make target exists on master

```
gibi@bedrock:~/upstream/git/openstack-k8s-operators/openstack-operator [master]                                                                                                                     [000] [10:40:33]
$ git pull
X11 forwarding request failed on channel 0
remote: Enumerating objects: 49, done.
remote: Counting objects: 100% (49/49), done.
remote: Compressing objects: 100% (21/21), done.
remote: Total 49 (delta 28), reused 44 (delta 26), pack-reused 0
Unpacking objects: 100% (49/49), 38.87 KiB | 199.00 KiB/s, done.
From github.com:openstack-k8s-operators/openstack-operator
   804c187..b46cc6c  master                                                                     -> origin/master
 * [new branch]      dependabot/go_modules/go.uber.org/zap-1.24.0                               -> origin/dependabot/go_modules/go.uber.org/zap-1.24.0
 * [new branch]      renovate/deps                                                              -> origin/renovate/deps
 + dbe87a7...90d0cbc renovate/github.com-openstack-k8s-operators-cinder-operator-api-digest     -> origin/renovate/github.com-openstack-k8s-operators-cinder-operator-api-digest  (forced update)
 * [new branch]      renovate/github.com-openstack-k8s-operators-glance-operator-api-digest     -> origin/renovate/github.com-openstack-k8s-operators-glance-operator-api-digest
 + d96e07a...e898f06 renovate/github.com-openstack-k8s-operators-keystone-operator-api-digest   -> origin/renovate/github.com-openstack-k8s-operators-keystone-operator-api-digest  (forced update)
 + 6627e54...1e87ced renovate/github.com-openstack-k8s-operators-openstack-operator-apis-digest -> origin/renovate/github.com-openstack-k8s-operators-openstack-operator-apis-digest  (forced update)
 * [new branch]      renovate/major-deps                                                        -> origin/renovate/major-deps
Updating 804c187..b46cc6c
Fast-forward
 .github/create_bundle.sh                               | 0
 .github/create_opm_index.sh                            | 0
 .pre-commit-config.yaml                                | 4 ++++
 config/samples/core_v1beta1_openstackcontrolplane.yaml | 2 +-
 containers/ci/Dockerfile                               | 3 ++-
 5 files changed, 7 insertions(+), 2 deletions(-)
 mode change 100644 => 100755 .github/create_bundle.sh
 mode change 100644 => 100755 .github/create_opm_index.sh
gibi@bedrock:~/upstream/git/openstack-k8s-operators/openstack-operator [master]                                                                                                                     [000] [10:40:36]
$ make operator-lint 
test -f go.work || go work init
go work use .
go work use ./apis
GOBIN=/home/gibi/upstream/git/openstack-k8s-operators/openstack-operator/bin go install github.com/gibizer/operator-lint@latest
go vet -vettool=/home/gibi/upstream/git/openstack-k8s-operators/openstack-operator/bin/operator-lint ./... ./apis/...
gibi@bedrock:~/upstream/git/openstack-k8s-operators/openstack-operator [master]                                                                                                     
```
It was added in https://github.com/openstack-k8s-operators/openstack-operator/pull/44

**Comment by dprince** [comment]
@gibizer oh, it does exist. But it is failing in CI with

make-operator-lint.......................................................Failed
- hook id: make-operator-lint
- exit code: 2

test -f go.work || go work init
go work use .
go: no go.work file found
	(run 'go work init' first or specify path using GOWORK environment variable)

**Comment by dprince** [comment]
'GOWORK=off' is set in our environment in order to get some other tasks passing. perhaps related

**Comment by dprince** [comment]
@gibizer @viroel I'm playing with a path to remove the operator-lint task and make it its own shell script in openstack-k8s-operators-ci which we can call in multiple places. The biggest issue I'm hitting right now is that the 'operator-lint' Makefile target creates go.work but doesn't cleanup after itself. That shouldn't be as it causes other side effects.

**Comment by dprince** [comment]
Thinking if it is a standalone script we can use a trap function to cleanup or something

**Comment by gibizer** [comment]
> 'GOWORK=off' is set in our environment in order to get some other tasks passing. perhaps related
To be able to run lints on both /apis and the main module in the repo we need the go.work file and by setting GOWORK=off the `go work init` in the make target simply skipped. This causing the error at `go work use .
`

**Pull request closed without merging**
