### PR TITLE
[tempest]Enable vTPM testing

### PR DESCRIPTION
**Pull request by gibizer**
This ensures that the Barbican - Nova integration works.

Implements: https://issues.redhat.com/browse/OSPRH-2449
Implements: https://issues.redhat.com/browse/OSPRH-2451
Depends-On: https://github.com/openstack-k8s-operators/edpm-ansible/pull/537

### CODE REVIEW

**Comment by gibizer** [comment]
somebody does not telling me the full truth:

https://review.rdoproject.org/zuul/build/710edf6bab7e48fdb7f8d8195611eb3f/log/controller/ci-framework-data/tests/tempest/podman_tempest.log#46
```
2023-12-07 14:57:45.770 8 DEBUG config_tempest.constants [-] Setting [compute_feature_enabled] vtpm_device_supported = True set /usr/lib/python3.9/site-packages/config_tempest/tempest_conf.py:105[00m
```

https://review.rdoproject.org/zuul/build/710edf6bab7e48fdb7f8d8195611eb3f/log/controller/ci-framework-data/tests/tempest/podman_tempest.log#206
```
{2} setUpClass (whitebox_tempest_plugin.api.compute.test_vtpm.VTPMTest) ... SKIPPED: CONF.compute_feature_enabled.vtpm_device_supported must be set.
```

**Comment by gibizer** [comment]
```
ft1.1: setUpClass (whitebox_tempest_plugin.api.compute.test_vtpm.VTPMTest)testtools.testresult.real._StringException: Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/tempest/test.py", line 206, in setUpClass
    raise value.with_traceback(trace)
  File "/usr/lib/python3.9/site-packages/tempest/test.py", line 196, in setUpClass
    cls.setup_clients()
  File "/usr/local/whitebox-tempest-plugin/whitebox_tempest_plugin/api/compute/test_vtpm.py", line 50, in setup_clients
    cls.os_primary.secrets_client = service_clients.secret_v1.SecretClient(
AttributeError: 'ServiceClients' object has no attribute 'secret_v1'
```

**Comment by gibizer** [comment]
> ```
> ft1.1: setUpClass (whitebox_tempest_plugin.api.compute.test_vtpm.VTPMTest)testtools.testresult.real._StringException: Traceback (most recent call last):
>   File "/usr/lib/python3.9/site-packages/tempest/test.py", line 206, in setUpClass
>     raise value.with_traceback(trace)
>   File "/usr/lib/python3.9/site-packages/tempest/test.py", line 196, in setUpClass
>     cls.setup_clients()
>   File "/usr/local/whitebox-tempest-plugin/whitebox_tempest_plugin/api/compute/test_vtpm.py", line 50, in setup_clients
>     cls.os_primary.secrets_client = service_clients.secret_v1.SecretClient(
> AttributeError: 'ServiceClients' object has no attribute 'secret_v1'
> ```

In a working job we have both whitebox and barbican tempest plugin loaded
```
2023-12-08 19:11:33.839 101156 INFO tempest.test_discover.plugins [-] Register additional config options from Tempest plugin: barbican_tests
2023-12-08 19:11:33.840 101156 INFO tempest.test_discover.plugins [-] Register additional config options from Tempest plugin: whitebox-tempest-plugin
2023-12-08 19:11:33.840 101156 INFO tempest.test_discover.plugins [-] List additional config options registered by Tempest plugin: barbican_tests
2023-12-08 19:11:33.840 101156 INFO tempest.test_discover.plugins [-] List additional config options registered by Tempest plugin: whitebox-tempest-plugin
```
But in this job we only have whitebox 
```
2023-12-08 17:54:59.325 7 INFO tempest [-] Using tempest config file /etc/tempest/tempest.conf[00m
2023-12-08 17:54:59.328 7 INFO tempest.test_discover.plugins [-] Register additional config options from Tempest plugin: whitebox-tempest-plugin[00m
2023-12-08 17:54:59.328 7 INFO tempest.test_discover.plugins [-] List additional config options registered by Tempest plugin: whitebox-tempest-plugin[00m
2023-12-08 17:54:59.340 7 INFO tempest.test_discover.plugins [-] List additional config options registered by Tempest plugin: whitebox-tempest-plugin[00m
~/openshift ~ /
2023-12-08 17:55:00.014 8 INFO tempest [-] Using tempest config file /var/lib/tempest/openshift/etc/tempest.conf[00m
```
This is why the secret client is not registered

**Comment by gibizer** [comment]
Adding the missing depedency to the image https://github.com/openstack-k8s-operators/tcib/pull/113

**Comment by gibizer** [comment]
Since https://github.com/openstack-k8s-operators/tcib/pull/112 merged we expect to have an openstack-tempest-all container image with all the plugins installed.

**Comment by gibizer** [comment]
Either we need 
* https://github.com/openstack-k8s-operators/tcib/pull/115 to add whitebox to tempest-all
OR
* https://github.com/openstack-k8s-operators/tcib/pull/113 to add barbican to tempest-extras

**Comment by gibizer** [comment]
recheck 
https://github.com/openstack-k8s-operators/tcib/pull/113 merged and container image is built to quay

**Comment by gibizer** [comment]
Hm it seems that even though the last image build was after the tcib commit was merged, the image does not contain the tcib change.
```
2023-12-19 09:21:13.238 7 INFO tempest [-] Using tempest config file /etc/tempest/tempest.conf[00m
2023-12-19 09:21:13.244 7 INFO tempest.test_discover.plugins [-] Register additional config options from Tempest plugin: whitebox-tempest-plugin[00m
2023-12-19 09:21:13.245 7 INFO tempest.test_discover.plugins [-] Register additional config options from Tempest plugin: manila_tests[00m
2023-12-19 09:21:13.246 7 INFO tempest.test_discover.plugins [-] List additional config options registered by Tempest plugin: whitebox-tempest-plugin[00m
2023-12-19 09:21:13.246 7 INFO tempest.test_discover.plugins [-] List additional config options registered by Tempest plugin: manila_tests[00m
2023-12-19 09:21:13.258 7 INFO tempest.test_discover.plugins [-] List additional config options registered by Tempest plugin: whitebox-tempest-plugin[00m
2023-12-19 09:21:13.259 7 INFO tempest.test_discover.plugins [-] List additional config options registered by Tempest plugin: manila_tests[00m
```

**Comment by gibizer** [comment]
> Hm it seems that even though the last image build was after the tcib commit was merged, the image does not contain the tcib change.
> 
> ```
> 2023-12-19 09:21:13.238 7 INFO tempest [-] Using tempest config file /etc/tempest/tempest.conf�[00m
> 2023-12-19 09:21:13.244 7 INFO tempest.test_discover.plugins [-] Register additional config options from Tempest plugin: whitebox-tempest-plugin�[00m
> 2023-12-19 09:21:13.245 7 INFO tempest.test_discover.plugins [-] Register additional config options from Tempest plugin: manila_tests�[00m
> 2023-12-19 09:21:13.246 7 INFO tempest.test_discover.plugins [-] List additional config options registered by Tempest plugin: whitebox-tempest-plugin�[00m
> 2023-12-19 09:21:13.246 7 INFO tempest.test_discover.plugins [-] List additional config options registered by Tempest plugin: manila_tests�[00m
> 2023-12-19 09:21:13.258 7 INFO tempest.test_discover.plugins [-] List additional config options registered by Tempest plugin: whitebox-tempest-plugin�[00m
> 2023-12-19 09:21:13.259 7 INFO tempest.test_discover.plugins [-] List additional config options registered by Tempest plugin: manila_tests�[00m
> ```

The image points to 
https://trunk.rdoproject.org/centos9-antelope/current-podified/8f/cc/8fcc848d6c766b48142f0ffef9e34937/delorean.repo
that points to tcib
https://github.com/openstack-k8s-operators/tcib/commit/7bf4dba1708c55fa9b3a0c929f18084c85bfe3d6
So the tcib#113 hasn't been built yet

**Comment by dprince** [comment]
Just rebased this, lets see if it passes now

**Comment by gibizer** [comment]
recheck lets see if we have a fresh tempest extras image with the barbican addition

**Comment by gibizer** [comment]
Finally we have the vtpm tests and barbican available in the same env, so the tests starts. The tests still fails but now on the compute with swtpm error:
```
: libvirt.libvirtError: operation failed: swtpm died and reported:
2024-01-15 12:14:32.411 2 ERROR nova.virt.libvirt.guest Traceback (most recent call last):
2024-01-15 12:14:32.411 2 ERROR nova.virt.libvirt.guest   File "/usr/lib/python3.9/site-packages/nova/virt/libvirt/guest.py", line 165, in launch
2024-01-15 12:14:32.411 2 ERROR nova.virt.libvirt.guest     return self._domain.createWithFlags(flags)
2024-01-15 12:14:32.411 2 ERROR nova.virt.libvirt.guest   File "/usr/lib/python3.9/site-packages/eventlet/tpool.py", line 193, in doit
2024-01-15 12:14:32.411 2 ERROR nova.virt.libvirt.guest     result = proxy_call(self._autowrap, f, *args, **kwargs)
2024-01-15 12:14:32.411 2 ERROR nova.virt.libvirt.guest   File "/usr/lib/python3.9/site-packages/eventlet/tpool.py", line 151, in proxy_call
2024-01-15 12:14:32.411 2 ERROR nova.virt.libvirt.guest     rv = execute(f, *args, **kwargs)
2024-01-15 12:14:32.411 2 ERROR nova.virt.libvirt.guest   File "/usr/lib/python3.9/site-packages/eventlet/tpool.py", line 132, in execute
2024-01-15 12:14:32.411 2 ERROR nova.virt.libvirt.guest     six.reraise(c, e, tb)
2024-01-15 12:14:32.411 2 ERROR nova.virt.libvirt.guest   File "/usr/lib/python3.9/site-packages/six.py", line 709, in reraise
2024-01-15 12:14:32.411 2 ERROR nova.virt.libvirt.guest     raise value
2024-01-15 12:14:32.411 2 ERROR nova.virt.libvirt.guest   File "/usr/lib/python3.9/site-packages/eventlet/tpool.py", line 86, in tworker
2024-01-15 12:14:32.411 2 ERROR nova.virt.libvirt.guest     rv = meth(*args, **kwargs)
2024-01-15 12:14:32.411 2 ERROR nova.virt.libvirt.guest   File "/usr/lib64/python3.9/site-packages/libvirt.py", line 1409, in createWithFlags
2024-01-15 12:14:32.411 2 ERROR nova.virt.libvirt.guest     raise libvirtError('virDomainCreateWithFlags() failed')
2024-01-15 12:14:32.411 2 ERROR nova.virt.libvirt.guest libvirt.libvirtError: operation failed: swtpm died and reported: 
2024-01-15 12:14:32.411 2 ERROR nova.virt.libvirt.guest 
2024-01-15 12:14:32.416 2 ERROR nova.virt.libvirt.driver [None req-acf52b90-9ec7-4da7-8a30-2721e89bf1bc 3660a18f0a42438fb5bc85b678006c16 d33f2a21efe34ebda79fc27eef8db806 - - default default] [instance: b5d96241-d569-4566-acfe-4edec9413a2f] Failed to start libvirt guest: libvirt.libvirtError: operation failed: swtpm died and reported:
```

**Comment by gibizer** [comment]
I can reproduce it locally with the same result. If I set `setenforce 0` on the compute then the VM boots with VTPM  so it is a selinux issue. Setting root to swtpm_user and  swtpm_group  in qemu.conf does not help.

**Comment by gibizer** [comment]
Fix is proposed to edpm_ansible https://github.com/openstack-k8s-operators/edpm-ansible/pull/537

**Comment by gibizer** [comment]
recheck

The selinux config in https://github.com/openstack-k8s-operators/edpm-ansible/pull/537 merged and a new runner image is built.

**Comment by gibizer** [comment]
We discussed on the #rhos-compute channel and there is an effort downstream to enable whitebox tests already but the compute_nodes.yaml configuration for whitebox is not ready yet. So let's close this for now not to duplicate the effort in parallel. Later we can revisit to move some of the downstream testing upstream.

**Pull request closed without merging**
