### PR TITLE
Cleanup stale ip reservations when scaling in nodeset

### PR DESCRIPTION
**Pull request by rabi**
Otherwise it won't be possible to use the same fixed ip addresses for a different node.

Jira: https://issues.redhat.com/browse/OSPRH-9704

### CODE REVIEW

**Review by fao89 — APPROVED** [review]

**Review by fao89 — APPROVED** [review]

**Comment by rabi** [comment]
recheck

**Comment by rabi** [comment]
`error: build error: Failed to push image: trying to reuse blob sha256:247c2d03e9487628cb6754ff5385a670df160f7bba36af8fc1f2066e461dc36e at destination: pinging container registry quay.rdoproject.org: Get "https://quay.rdoproject.org/v2/": dial tcp 38.129.56.158:443: i/o timeout`

**Review by fao89 — APPROVED** [review]

**Review by fao89 — APPROVED** [review]

**Pull request merged**
