### PR TITLE
FIPS support for RabbitMQ

### PR DESCRIPTION
**Pull request by Akrog**
When the OCP cluster is deployed in FIPS mode RabbitMQ needs to be deployed with specific parameters to also enable its FIPS mode.

This patch checks when OCP is running in FIPS mode using lib-common and changes the environmental variables used to deploy RabbitMQ just like we did in TripleO [1].

[1]: https://opendev.org/openstack/puppet-tripleo/src/commit/019ec495180d2065a172861554df2ba2a76b5b17/manifests/profile/base/rabbitmq.pp#L176

Jira: #[OSPRH-4668](https://issues.redhat.com//browse/OSPRH-4668)
Depends-On: https://github.com/openstack-k8s-operators/lib-common/pull/448

### CODE REVIEW

**Comment by Akrog** [comment]
recheck

**Review by stuggi — APPROVED** [review]
/lgtm

**Comment by stuggi** [comment]
ci failure test_live_block_migration_with_attached_volume  is unrelated to this change

**Pull request merged**
