### PR TITLE
[kuttl] Add tls scenarios for non API services

### PR DESCRIPTION
**Pull request by Deydra71**

### CODE REVIEW

**Comment by jpodivin** [comment]
Hi. The script itself is working. It reports mismatches and other issues as expected. However, do we want the test to pass even if there are issues? Because as it is, the step is just going to deposit info about it in logs.

**Review by jpodivin — COMMENTED** [review]
Hi. The script itself is working. It reports mismatches and other issues as expected. However, do we want the test to pass even if there are issues? Because as it is, the step is just going to deposit info about it in logs.

**Comment by Deydra71** [comment]
@jpodivin 
Hello, yes I know. I keep it like this until I get a review from @stuggi  or @olliewalsh what's their preferred approach

**Comment by olliewalsh** [comment]
> Hi. The script itself is working. It reports mismatches and other issues as expected. However, do we want the test to pass even if there are issues? Because as it is, the step is just going to deposit info about it in logs.

? returns 1 IIUC - https://github.com/openstack-k8s-operators/openstack-operator/pull/1168/files#diff-291551847705ed67b32c66c3659c73adee6d1b07693a5b08ab9f288f274cd0e7R57

**Comment by Deydra71** [comment]
@olliewalsh  It was a misunderstanding that the script returns 1, but the kuttl doesn't fail immediately, but tries again until the timeout. All clear now.

**Review by stuggi — COMMENTED** [review]
looks good to me, but maybe we could extend it for the db ?

**Comment by stuggi** [comment]
> looks good to me, but maybe we could extend it for the db ?

strange my inline comment was lost. for the db can use `openssl s_client -starttls mysql -connect ...`

**Review by stuggi — APPROVED** [review]
/lgtm

**Pull request merged**
