### PR TITLE
Set Octavia route annotations

### PR DESCRIPTION
**Pull request by fernandoroyosanchez**
Depends-On: https://github.com/openstack-k8s-operators/octavia-operator/pull/412
Related-Issue: [OSPRH-10959](https://issues.redhat.com//browse/OSPRH-10959)

### CODE REVIEW

**Comment by fernandoroyosanchez** [comment]
recheck

**Comment by fernandoroyosanchez** [comment]
recheck

**Comment by fernandoroyosanchez** [comment]
Failing job [openstack-k8s-operators-content-provider ](https://softwarefactory-project.io/zuul/t/rdoproject.org/build/7aa9ed4505ae4c8ab16ec19de0919a34) due to:
github account: fernandoroyosanchez
quay.io account: froyo
It is trying to found the tag in https://quay.io/api/v1/repository/fernandoroyosanchez/octavia-operator-bundle/tag/?onlyActiveTags=true\&filter_tag_name=like:1c6bb990d622 instead of https://quay.io/api/v1/repository/froyo/octavia-operator-bundle/tag/?onlyActiveTags=true\&filter_tag_name=like:1c6bb990d622

**Comment by viroel** [comment]
recheck

**Comment by viroel** [comment]
recheck

**Comment by viroel** [comment]
recheck

**Comment by abays** [comment]
> @fernandoroyosanchez: The following test **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:
> Test name 	Commit 	Details 	Required 	Rerun command
> ci/prow/openstack-operator-build-deploy-kuttl 	[c8f261b](https://github.com/openstack-k8s-operators/openstack-operator/commit/c8f261b079f77436a860a92836eb0f4a5ed6dabf) 	[link](https://prow.ci.openshift.org/view/gs/test-platform-results/pr-logs/pull/openstack-k8s-operators_openstack-operator/1175/pull-ci-openstack-k8s-operators-openstack-operator-main-openstack-operator-build-deploy-kuttl/1856635780651290624) 	true 	`/test openstack-operator-build-deploy-kuttl`
> 
> [Full PR test history](https://prow.ci.openshift.org/pr-history?org=openstack-k8s-operators&repo=openstack-operator&pr=1175). [Your PR dashboard](https://prow.ci.openshift.org/pr?query=is:pr+state:open+author:fernandoroyosanchez).

```
Error from server (InternalError): error when creating "https://raw.githubusercontent.com/openstack-k8s-operators/infra-operator/main/config/samples/network_v1beta1_netconfig.yaml": Internal error occurred: failed calling webhook "mnetconfig.kb.io": failed to call webhook: Post "https://infra-operator-controller-manager-service.openstack-operators.svc:443/mutate-network-openstack-org-v1beta1-netconfig?timeout=10s": no endpoints available for service "infra-operator-controller-manager-service"
```

/test openstack-operator-build-deploy-kuttl

**Comment by fernandoroyosanchez** [comment]
`dial tcp 38.129.56.158:443: i/o timeout`

**Comment by fernandoroyosanchez** [comment]
`dial tcp 38.129.56.158:443: i/o timeout `
/retest

**Comment by fernandoroyosanchez** [comment]
recheck

**Comment by fernandoroyosanchez** [comment]
recheck

**Comment by fernandoroyosanchez** [comment]
recheck

**Comment by abays** [comment]
> @fernandoroyosanchez: The following tests **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:
> Test name 	Commit 	Details 	Required 	Rerun command
> ci/prow/images 	[c0eb730](https://github.com/openstack-k8s-operators/openstack-operator/commit/c0eb73046ef9873174595fe51566a7054eaf8706) 	[link](https://prow.ci.openshift.org/view/gs/test-platform-results/pr-logs/pull/openstack-k8s-operators_openstack-operator/1175/pull-ci-openstack-k8s-operators-openstack-operator-main-images/1858555582194126848) 	unknown 	`/test images`
> ci/prow/precommit-check 	[c0eb730](https://github.com/openstack-k8s-operators/openstack-operator/commit/c0eb73046ef9873174595fe51566a7054eaf8706) 	[link](https://prow.ci.openshift.org/view/gs/test-platform-results/pr-logs/pull/openstack-k8s-operators_openstack-operator/1175/pull-ci-openstack-k8s-operators-openstack-operator-main-precommit-check/1858555582261235712) 	unknown 	`/test precommit-check`
> ci/prow/functional 	[c0eb730](https://github.com/openstack-k8s-operators/openstack-operator/commit/c0eb73046ef9873174595fe51566a7054eaf8706) 	[link](https://prow.ci.openshift.org/view/gs/test-platform-results/pr-logs/pull/openstack-k8s-operators_openstack-operator/1175/pull-ci-openstack-k8s-operators-openstack-operator-main-functional/1858555581653061632) 	unknown 	`/test functional`
> 
> [Full PR test history](https://prow.ci.openshift.org/pr-history?org=openstack-k8s-operators&repo=openstack-operator&pr=1175). [Your PR dashboard](https://prow.ci.openshift.org/pr?query=is:pr+state:open+author:fernandoroyosanchez).

Never seen this one before:

```
Copying blob sha256:91a417dae5d3903326cb3c8ade2ca25613b35b6b44b8498b12afd3d9a51821df, the build src-amd64 failed after 5m34s with reason OutOfMemoryKilled: The build pod was killed due to an out of memory condition.
```

Let's see if it happens again.

/retest

**Pull request merged**
