### PR TITLE
[18.0.0-proposed] Backport of name validation for mariadb, rabbitmq, memcached, cinder, and glance

### PR DESCRIPTION
**Pull request by stuggi**
Backport of the following validation PRs:
* https://github.com/openstack-k8s-operators/openstack-operator/pull/927
* https://github.com/openstack-k8s-operators/openstack-operator/pull/947
* https://github.com/openstack-k8s-operators/openstack-operator/pull/952
* https://github.com/openstack-k8s-operators/openstack-operator/pull/955
* https://github.com/openstack-k8s-operators/openstack-operator/pull/957

Jira: https://issues.redhat.com/browse/OSPRH-8063

### CODE REVIEW

**Review by abays — APPROVED** [review]
/lgtm

**Comment by stuggi** [comment]
recheck

**Review by jpodivin — APPROVED** [review]

**Pull request merged**
