### PR TITLE
Updating to the latest working version of dataplane

### PR DESCRIPTION
**Pull request by fao89**

### CODE REVIEW

**Comment by fao89** [comment]
recheck

**Comment by fao89** [comment]
recheck

**Comment by fao89** [comment]
recheck

**Comment by cescgina** [comment]
@fao89 we can try to add https://github.com/openstack-k8s-operators/openstack-operator/pull/723 as depends-on, it seems to fix the content-provider issue

**Comment by fao89** [comment]
recheck

**Comment by fao89** [comment]
recheck

**Comment by fao89** [comment]
recheck

**Comment by fao89** [comment]
recheck

**Comment by fao89** [comment]
recheck

**Comment by fao89** [comment]
recheck

**Comment by fao89** [comment]
recheck

**Comment by fao89** [comment]
recheck

**Comment by abays** [comment]
This one just had bad luck with CI randomness.  https://github.com/openstack-k8s-operators/openstack-operator/pull/725 seems to have superseded it.

**Pull request closed without merging**
