### PR TITLE
[ovn-controller] Don't create ovn-controller if nicMappings empty

### PR DESCRIPTION
**Pull request by averdagu**
If nicMappings is empty on the ovn/ovn-controller section don't spawn the ovn-controller as it won't do anything.

Resolves: [OSPRH-7463](https://issues.redhat.com//browse/OSPRH-7463)

### CODE REVIEW

**Review by booxter — CHANGES_REQUESTED** [review]
Please fix test failures and make sure that we have test coverage both for the "empty nicMappings" and proper configuration.

**Comment by averdagu** [comment]
Functional tests should be fixed now, working on kuttl

**Comment by averdagu** [comment]
recheck

**Review by bshephar — APPROVED** [review]
Looks good to me, nice to have a test for it.

**Pull request merged**
