### PR TITLE
[openstackclient] Update controller to watch named input resources

### PR DESCRIPTION
**Pull request by stuggi**
Adds watches for name secret and configmap resources from the OpenStackClient CRD. This allows to watch the specific resources when they change.

Also adds EnvTest for OpenstackClient being created by the OpenstackControlPlane controller.

Depends-On: https://github.com/openstack-k8s-operators/lib-common/pull/428

### CODE REVIEW

**Review by olliewalsh — APPROVED** [review]
/lgtm

**Comment by stuggi** [comment]
known kernel panic in baremetal job https://logserver.rdoproject.org/19/619/9ef32a0f2eb7739f39ec69af7fa6ca3f030f186c/github-check/cifmw-crc-podified-edpm-baremetal/adf4a96/ci-framework-data/logs/bmaas_console_logs/edpm-compute-01_console.log - going to override zuul due to baremetal job issue and the PR does not have an impact on baremetal

**Pull request merged**
