### PR TITLE
Updating to the latest working version of telemetry

### PR DESCRIPTION
**Pull request by jlarriba**

### CODE REVIEW

**Review by dprince — APPROVED** [review]

**Comment by dprince** [comment]
recheck

**Comment by dprince** [comment]
only the adoption RDO jobs failed last time, if we see that pass we should merge it

**Comment by dprince** [comment]
recheck

**Comment by jlarriba** [comment]
recheck

**Comment by jlarriba** [comment]
recheck

**Comment by olliewalsh** [comment]
recheck

**Pull request closed without merging**
