### PR TITLE
[TLS] add wild card hostnames for headless galera/rabbitmq svc

### PR DESCRIPTION
**Pull request by stuggi**
For tls cluster interconnect add wild card for the services headless service names.

### CODE REVIEW

**Comment by dciabrin** [comment]
recheck

**Comment by olliewalsh** [comment]
recheck

**Comment by stuggi** [comment]
recheck

**Comment by stuggi** [comment]
recheck

**Comment by stuggi** [comment]
recheck

**Review by Deydra71 — APPROVED** [review]

**Pull request merged**
