### PR TITLE
[DNM] checking extracted crc content provider support

### PR DESCRIPTION
**Pull request by raukadah**
Depends-On: https://github.com/openstack-k8s-operators/ci-framework/pull/379

### CODE REVIEW

**Comment by raukadah** [comment]
recheck

**Comment by raukadah** [comment]
recheck

**Comment by raukadah** [comment]
recheck

**Comment by raukadah** [comment]
recheck

**Comment by raukadah** [comment]
recheck

**Comment by raukadah** [comment]
recheck

**Comment by raukadah** [comment]
recheck

**Comment by raukadah** [comment]
recheck

**Comment by raukadah** [comment]
https://logserver.rdoproject.org/95/395/d6145ad31c88f86fc0f706bc1d61a73086d9606c/github-check/openstack-operator-crc-extended-podified-deployment/5a4f405/job-output.txt
```
TASK [run_hook : Run /home/zuul/src/github.com/openstack-k8s-operators/ci-framework/ci_framework/roles/run_hook/../../hooks/playbooks/fetch_compute_facts.yml playbook create={{ hook.creates | default(omit) }}, _raw_params=ansible-playbook -i {{ hook.inventory | default(inventory_file) }} {{ extra_vars }} -e "cifmw_basedir={{ cifmw_basedir }}" -e "step={{ step }}" -e "hook_name={{ hook_name }}" -e "playbook_dir={{ playbook_path | dirname }}" {{ playbook_path }}] ***
2023-07-17 06:31:43.272944 | controller | Monday 17 July 2023  06:31:43 -0400 (0:00:00.072)       0:01:06.026 ***********
2023-07-17 06:31:44.301040 | controller | fatal: [localhost]: FAILED! => {"changed": true, "cmd": ["ansible-playbook", "-i", "/home/zuul/ci-framework-data/artifacts/zuul_inventory.yml", "-e", "@/home/zuul/ci-framework-data/artifacts/parameters/install-yamls-params.yml", "-e", "@/home/zuul/ci-framework-data/artifacts/parameters/custom-params.yml", "-e", "@/home/zuul/ci-framework-data/artifacts/parameters/openshift-login-params.yml", "-e", "cifmw_basedir=/home/zuul/ci-framework-data", "-e", "step=post_infra", "-e", "hook_name=fetch_nodes_facts_and_safe_them_as_parameters", "-e", "playbook_dir=/home/zuul/src/github.com/openstack-k8s-operators/ci-framework/ci_framework/roles/run_hook/../../hooks/playbooks", "/home/zuul/src/github.com/openstack-k8s-operators/ci-framework/ci_framework/roles/run_hook/../../hooks/playbooks/fetch_compute_facts.yml"], "delta": "0:00:00.714879", "end": "2023-07-17 06:31:44.249949", "msg": "non-zero return code", "rc": 2, "start": "2023-07-17 06:31:43.535070", "stderr": "", "stderr_lines": [], "stdout": "\nPLAY [localhost] ***************************************************************\n\nTASK [Ensure we know compute host keys _raw_params=ssh-keyscan {{ hostvars.compute.ansible_host }} >> ~/.ssh/known_hosts\n] ***\nMonday 17 July 2023  06:31:44 -0400 (0:00:00.032)       0:00:00.032 *********** \nfatal: [localhost]: FAILED! => {\"msg\": \"The task includes an option with an undefined variable. The error was: \\\"hostvars['compute']\\\" is undefined. \\\"hostvars['compute']\\\" is undefined\\n\\nThe error appears to be in '/home/zuul/src/github.com/openstack-k8s-operators/ci-framework/ci_framework/hooks/playbooks/fetch_compute_facts.yml': line 6, column 7, but may\\nbe elsewhere in the file depending on the exact syntax problem.\\n\\nThe offending line appears to be:\\n\\n  tasks:\\n    - name: Ensure we know compute host keys\\n      ^ here\\n\"}\n\nPLAY RECAP *********************************************************************\nlocalhost                  : ok=0    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0   \n\nMonday 17 July 2023  06:31:44 -0400 (0:00:00.020)       0:00:00.053 *********** \n=============================================================================== \nEnsure we know compute host keys ---------------------------------------- 0.02s", "stdout_lines": ["", "PLAY [localhost] ***************************************************************", "", "TASK [Ensure we know compute host keys _raw_params=ssh-keyscan {{ hostvars.compute.ansible_host }} >> ~/.ssh/known_hosts", "] ***", "Monday 17 July 2023  06:31:44 -0400 (0:00:00.032)       0:00:00.032 *********** ", "fatal: [localhost]: FAILED! => {\"msg\": \"The task includes an option with an undefined variable. The error was: \\\"hostvars['compute']\\\" is undefined. \\\"hostvars['compute']\\\" is undefined\\n\\nThe error appears to be in '/home/zuul/src/github.com/openstack-k8s-operators/ci-framework/ci_framework/hooks/playbooks/fetch_compute_facts.yml': line 6, column 7, but may\\nbe elsewhere in the file depending on the exact syntax problem.\\n\\nThe offending line appears to be:\\n\\n  tasks:\\n    - name: Ensure we know compute host keys\\n      ^ here\\n\"}", "", "PLAY RECAP *********************************************************************", "localhost                  : ok=0    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0   ", "", "Monday 17 July 2023  06:31:44 -0400 (0:00:00.020)       0:00:00.053 *********** ", "=============================================================================== ", "Ensure we know compute host keys ---------------------------------------- 0.02s"]}
```

**Comment by stuggi** [comment]
@raukadah you still use this, or can we close it?

**Comment by dprince** [comment]
this looks stale, please re-open if needed

**Pull request closed without merging**
