### PR TITLE
Fixing style issues

### PR DESCRIPTION
**Pull request by jpodivin**
- Two error messages didn't comply with recommended style. It's largely irrelevant but it was polluting my IDE.
- One comment had a typo
- Annotations were inconsistently formatted (I'm not completely sold on this one, it's technically fine either way and it may pollute blame, I'll drop it if there is a push back)

### CODE REVIEW

**Review by fao89 — APPROVED** [review]

**Comment by jpodivin** [comment]
/restest

` error: build error: Failed to push image: trying to reuse blob`

**Review by fao89 — APPROVED** [review]

**Pull request merged**
