### PR TITLE
Force bump for renovate to catch up

### PR DESCRIPTION
**Pull request by fao89**

### CODE REVIEW

**Comment by fao89** [comment]
recheck

**Review by gibizer — COMMENTED** [review]
From nova- and placement-operator this looks good. Thanks!

**Comment by gibizer** [comment]
Do we have a build failure in neutron-operator?
```
+ [[ quay.io != \q\u\a\y\.\i\o ]]
++ curl -s 'https://quay.io/api/v1/repository/openstack-k8s-operators/neutron-operator-bundle/tag/?filter_tag_name=like:d6bbc917719e'
++ jq -r '.tags[].name'
+ SHA=
+ '[' -z '' ']'
+ echo 'Error: SHA is empty, Could not find container with tag d6bbc917719e in https://quay.io/api/v1/repository/openstack-k8s-operators'
Error: SHA is empty, Could not find container with tag d6bbc917719e in https://quay.io/api/v1/repository/openstack-k8s-operators
```

**Comment by gibizer** [comment]
> Do we have a build failure in neutron-operator?
> 
> ```
> + [[ quay.io != \q\u\a\y\.\i\o ]]
> ++ curl -s 'https://quay.io/api/v1/repository/openstack-k8s-operators/neutron-operator-bundle/tag/?filter_tag_name=like:d6bbc917719e'
> ++ jq -r '.tags[].name'
> + SHA=
> + '[' -z '' ']'
> + echo 'Error: SHA is empty, Could not find container with tag d6bbc917719e in https://quay.io/api/v1/repository/openstack-k8s-operators'
> Error: SHA is empty, Could not find container with tag d6bbc917719e in https://quay.io/api/v1/repository/openstack-k8s-operators
> ```

Yepp we do https://github.com/openstack-k8s-operators/neutron-operator/actions/runs/5747638504
```
 Error: podman exited with code 125
Error: trying to reuse blob sha256:e023e0e48e6e29e90e519f4dd356d058ff2bffbd16e28b802f3b8f93aa4ccb17 at destination: Requesting bear token: invalid status code from registry 500 (Internal Server Error)
```

**Comment by gibizer** [comment]
> > Do we have a build failure in neutron-operator?
> > ```
> > + [[ quay.io != \q\u\a\y\.\i\o ]]
> > ++ curl -s 'https://quay.io/api/v1/repository/openstack-k8s-operators/neutron-operator-bundle/tag/?filter_tag_name=like:d6bbc917719e'
> > ++ jq -r '.tags[].name'
> > + SHA=
> > + '[' -z '' ']'
> > + echo 'Error: SHA is empty, Could not find container with tag d6bbc917719e in https://quay.io/api/v1/repository/openstack-k8s-operators'
> > Error: SHA is empty, Could not find container with tag d6bbc917719e in https://quay.io/api/v1/repository/openstack-k8s-operators
> > ```
> 
> Yepp we do https://github.com/openstack-k8s-operators/neutron-operator/actions/runs/5747638504
> 
> ```
>  Error: podman exited with code 125
> Error: trying to reuse blob sha256:e023e0e48e6e29e90e519f4dd356d058ff2bffbd16e28b802f3b8f93aa4ccb17 at destination: Requesting bear token: invalid status code from registry 500 (Internal Server Error)
> ```

I have triggered a new build

**Comment by gibizer** [comment]
> > > Do we have a build failure in neutron-operator?
> > > ```
> > > + [[ quay.io != \q\u\a\y\.\i\o ]]
> > > ++ curl -s 'https://quay.io/api/v1/repository/openstack-k8s-operators/neutron-operator-bundle/tag/?filter_tag_name=like:d6bbc917719e'
> > > ++ jq -r '.tags[].name'
> > > + SHA=
> > > + '[' -z '' ']'
> > > + echo 'Error: SHA is empty, Could not find container with tag d6bbc917719e in https://quay.io/api/v1/repository/openstack-k8s-operators'
> > > Error: SHA is empty, Could not find container with tag d6bbc917719e in https://quay.io/api/v1/repository/openstack-k8s-operators
> > > ```
> > 
> > 
> > Yepp we do https://github.com/openstack-k8s-operators/neutron-operator/actions/runs/5747638504
> > ```
> >  Error: podman exited with code 125
> > Error: trying to reuse blob sha256:e023e0e48e6e29e90e519f4dd356d058ff2bffbd16e28b802f3b8f93aa4ccb17 at destination: Requesting bear token: invalid status code from registry 500 (Internal Server Error)
> > ```
> 
> I have triggered a new build

The new build succeeded so the neutron bundle is now available

**Comment by slagle** [comment]
recheck

**Comment by fao89** [comment]
recheck

**Comment by slagle** [comment]
recheck

**Comment by fao89** [comment]
recheck

**Review by dprince — APPROVED** [review]

**Comment by slagle** [comment]
recheck

**Review by abays — APPROVED** [review]
/lgtm

**Comment by slagle** [comment]
recheck

**Comment by fao89** [comment]
recheck

**Comment by fao89** [comment]
recheck

**Comment by rabi** [comment]
recheck

**Comment by slagle** [comment]
recheck

**Comment by slagle** [comment]
recheck

**Pull request merged**
