### PR TITLE
Relocate OpenStackClient to OpenStack operator

### PR DESCRIPTION
**Pull request by abays**
We have agreed to move `OpenStackClient` to the OpenStack operator to fix an import cycle problem between Keystone and Infra operator

### CODE REVIEW

**Comment by abays** [comment]
```
{  failed to wait for the created cluster claim to become ready: timed out waiting for the condition}
```

/test openstack-operator-build-deploy-kuttl

**Comment by abays** [comment]
Zuul hiccup:

```
Internal error occurred: failed calling webhook \"vnetconfig.kb.io\": failed to call webhook: Post \"https://infra-operator-controller-manager-service.openstack-operators.svc:443/validate-network-openstack-org-v1beta1-netconfig?timeout=10s\": dial tcp 10.217.0.96:9443: connect: connection refused
```

**Comment by abays** [comment]
recheck

**Comment by abays** [comment]
recheck

**Review by dprince — APPROVED** [review]

**Comment by abays** [comment]
Zuul hiccup:

```
Error from server (InternalError): Internal error occurred: failed calling webhook \"mopenstackdataplane.kb.io\": failed to call webhook: Post \"https://dataplane-operator-controller-manager-service.openstack-operators.svc:443/mutate-dataplane-openstack-org-v1beta1-openstackdataplane?timeout=10s\": no endpoints available for service \"dataplane-operator-controller-manager-service\"
```

**Comment by abays** [comment]
recheck

**Comment by fao89** [comment]
recheck

**Comment by kajinamit** [comment]
/lgtm

I'll attempt to add kuttl test coverage once this is merged.

**Comment by rabi** [comment]
recheck

**Comment by rabi** [comment]
recheck

**Comment by rabi** [comment]
`2023-07-19 23:05:59.175970 | controller | TASK [os_net_setup : Process network list elements admin_state_up={{ net_args.admin_state_up | default(omit) }}, dns_domain={{ net_args.dns_domain | default(omit) }}, external={{ net_args.external | default(omit) }}, mtu={{ net_args.mtu | default(omit) }}, name={{ net_args.name | default(omit) }}, port_security_enabled={{ net_args.port_security_enabled | default(omit) }}, provider_network_type={{ net_args.provider_network_type | default(omit) }}, provider_physical_network={{ net_args.provider_physical_network | default(omit) }}, provider_segmentation_id={{ net_args.provider_segmentation_id | default(omit) }}, shared={{ net_args.shared | default(omit) }}, region_name={{ region_name }}, state=present, auth={{ openstack_auth }}] ***
2023-07-19 23:05:59.175980 | controller | Wednesday 19 July 2023  23:05:59 -0400 (0:00:00.050)       0:38:46.066 ********
2023-07-19 23:06:32.456986 | controller | fatal: [localhost]: FAILED! => {"changed": false, "extra_data": {"data": null, "details": "The server didn't respond in time.: 504 Gateway Time-out", "response": "<html><body><h1>504 Gateway Time-out</h1>\nThe server didn't respond in time.\n</body></html>\n"}, "msg": "HttpException: 504: Server Error for url: http://neutron-public-openstack.apps-crc.testing/v2.0/networks, The server didn't respond in time.: 504 Gateway Time-out"}
2023-07-19 23:06:32.457642 | controller |`

**Comment by rabi** [comment]
recheck

**Comment by rabi** [comment]
recheck

**Comment by fao89** [comment]
recheck

**Comment by fao89** [comment]
recheck

**Comment by fao89** [comment]
recheck

**Comment by abays** [comment]
If this keeps failing randomly one way or another due to hiccups, I am going to recommend we just force-merge it.  It is holding-up other people as they work towards dev preview finalization.

**Comment by fao89** [comment]
> If this keeps failing randomly one way or another due to hiccups, I am going to recommend we just force-merge it. It is holding-up other people as they work towards dev preview finalization.

should we merge?

**Comment by abays** [comment]
:cowboy_hat_face:

**Pull request merged**
