### PR TITLE
csv-merger: merge relatedImages

### PR DESCRIPTION
**Pull request by dprince**
We need to merge in relatedImages from the dataplane-operator

Also drops the extendedCsv struct as it is no longer needed

### CODE REVIEW

**Comment by abays** [comment]
This seems to pass CI, but it fails to build for me locally:

```
$ IMAGE_TAG_BASE=quay.io/andrewbays/openstack-operator VERSION=0.0.1 IMG=$IMAGE_TAG_BASE:v$VERSION make manifests build docker-build docker-push bundle bundle-build bundle-push catalog-build catalog-push

...

INFO[0004] Creating bundle.Dockerfile                   
INFO[0004] Creating bundle/metadata/annotations.yaml    
INFO[0004] Bundle metadata generated successfully       
operator-sdk bundle validate ./bundle
ERRO[0000] Error: Value client.openstack.org/v1beta1, Kind=OpenStackClient: CRD "client.openstack.org/v1beta1, Kind=OpenStackClient" is present in bundle "openstack-operator.v0.0.1" but not defined in CSV
...
```

Might just be something peculiar to my environment.

**Comment by dprince** [comment]
> This seems to pass CI, but it fails to build for me locally:
> 
> ```
> $ IMAGE_TAG_BASE=quay.io/andrewbays/openstack-operator VERSION=0.0.1 IMG=$IMAGE_TAG_BASE:v$VERSION make manifests build docker-build docker-push bundle bundle-build bundle-push catalog-build catalog-push
> 
> ...
> 
> INFO[0004] Creating bundle.Dockerfile                   
> INFO[0004] Creating bundle/metadata/annotations.yaml    
> INFO[0004] Bundle metadata generated successfully       
> operator-sdk bundle validate ./bundle
> ERRO[0000] Error: Value client.openstack.org/v1beta1, Kind=OpenStackClient: CRD "client.openstack.org/v1beta1, Kind=OpenStackClient" is present in bundle "openstack-operator.v0.0.1" but not defined in CSV
> ...
> ```
> 
> Might just be something peculiar to my environment.

I tried the bundle validate with operator-sdk 1.31 and it seems fine. Is it an older version in your environment? (we don't technically require 1.31 yet but soon will)

**Review by abays — APPROVED** [review]
/lgtm

**Pull request merged**
