### PR TITLE
Adding shortnames to match dataplane pattern

### PR DESCRIPTION
**Pull request by fao89**
https://github.com/openstack-k8s-operators/dataplane-operator/blob/main/api/v1beta1/openstackdataplane_types.go#L56C60-L56C71

### CODE REVIEW

**Review by abays — APPROVED** [review]
/lgtm

**Comment by fao89** [comment]
recheck

**Comment by fao89** [comment]
recheck

**Comment by fao89** [comment]
recheck

**Comment by fao89** [comment]
recheck

**Comment by abays** [comment]
Tests have passed independently across the various batched runs. Will override.

**Pull request merged**
