### PR TITLE
Adding patch rbac perm for serviceaccounts

### PR DESCRIPTION
**Pull request by jpodivin**
Resolves: https://issues.redhat.com/browse/OSPRH-8363

### CODE REVIEW

**Comment by gibizer** [comment]
/hold
until we branch to 18.0.0-proposed

**Comment by stuggi** [comment]
can you please add wherever we have update, but not patch, also the patch?

**Review by bshephar — APPROVED** [review]

**Comment by bshephar** [comment]
I tried to push to this PR branch, but it didn't love it. It just created a new branch on this repo. But this is the additional changes @stuggi is talking about I believe:
https://github.com/openstack-k8s-operators/openstack-operator/commit/2c7a889d18c963379a8c95d9e8df927fb1c99dba

I'll leave the branch there for now if you just want to cherry-pick it and squash with the existing change on this PR.

**Comment by stuggi** [comment]
> I tried to push to this PR branch, but it didn't love it. It just created a new branch on this repo. But this is the additional changes @stuggi is talking about I believe: [2c7a889](https://github.com/openstack-k8s-operators/openstack-operator/commit/2c7a889d18c963379a8c95d9e8df927fb1c99dba)
> 
> I'll leave the branch there for now if you just want to cherry-pick it and squash with the existing change on this PR.

yes correct, thanks @bshephar

**Comment by stuggi** [comment]
> > I tried to push to this PR branch, but it didn't love it. It just created a new branch on this repo. But this is the additional changes @stuggi is talking about I believe: [2c7a889](https://github.com/openstack-k8s-operators/openstack-operator/commit/2c7a889d18c963379a8c95d9e8df927fb1c99dba)
> > I'll leave the branch there for now if you just want to cherry-pick it and squash with the existing change on this PR.
> 
> yes correct, thanks @bshephar

@jpodivin @bshephar I have cherry-picked and squashed the two commits.

**Review by gibizer — APPROVED** [review]
Looks good, and it is a GA blocker

**Review by fmount — APPROVED** [review]
/lgtm

**Pull request merged**
