### PR TITLE
[WIP] Moving to 1.21

### PR DESCRIPTION
**Pull request by jpodivin**

### CODE REVIEW

**Comment by stuggi** [comment]
is this something we intend to do before GA? iirc last time we discussed that in the weekly sync call it was a post GA task, or has this changed?

**Comment by bshephar** [comment]
> is this something we intend to do before GA? iirc last time we discussed that in the weekly sync call it was a post GA task, or has this changed?

I think we're still aiming for post GA. There's a bunch of supporting work that needs to be done, so there's probably value in capturing where CI fails with this and recording what needs to happen to get it all passing.

I see it's been opened with [WIP], probably for that very reason. We can probably just mark this as draft once we've captured the CI failures.

**Comment by stuggi** [comment]
> > is this something we intend to do before GA? iirc last time we discussed that in the weekly sync call it was a post GA task, or has this changed?
> 
> I think we're still aiming for post GA. There's a bunch of supporting work that needs to be done, so there's probably value in capturing where CI fails with this and recording what needs to happen to get it all passing.
> 
> I see it's been opened with [WIP], probably for that very reason. We can probably just mark this as draft once we've captured the CI failures.

when I looked/commented it did not have the `[WIP]`, thanks for adding it!

**Comment by jpodivin** [comment]
> > > is this something we intend to do before GA? iirc last time we discussed that in the weekly sync call it was a post GA task, or has this changed?
> > 
> > 
> > I think we're still aiming for post GA. There's a bunch of supporting work that needs to be done, so there's probably value in capturing where CI fails with this and recording what needs to happen to get it all passing.
> > I see it's been opened with [WIP], probably for that very reason. We can probably just mark this as draft once we've captured the CI failures.
> 
> when I looked/commented it did not have the `[WIP]`, thanks for adding it!

That's on me. I forgot to put it there when I opened it. Sorry.

**Pull request closed without merging**
